### ISSUE TITLE
Permissions on files created inside /tmp/.dotnet are too open 

### ISSUE THREAD

**Issue by gorazdzagar** [dotnet/sdk#13130]
# Permissions on files created inside /tmp/.dotnet are too open 

While executing the **dotnet restore**, temporary file permissions created under the session subfolders inside /tmp/.dotnet/shm/ are too open.

# General

Dotnet SDK version: 3.1.302

While executing the **dotnet restore**, the build sessions subfolder is created under /tmp/.dotnet/shm/. 

Example:

/tmp/.dotnet/shm/session5550# ls -la
total 56
drwxrwxrwx 2 root root  4096 Aug 24 08:02 .
drwxrwxrwx 4 root root 36864 Aug 24 08:02 ..
-rw-rw-rw- 1 root root  4096 Aug 24 08:02 2467f586da4947fd99b79661ba0330fe
-rw-rw-rw- 1 root root  4096 Aug 24 08:02 f58babb546ad4d38a2a5afd2ed6511d1
-rw-rw-rw- 1 root root  4096 Aug 24 08:02 PiDh3VmOno5IZWwRHV_oNjZ+jcby9Rt5wuWKeDyQUJY.server

Folder as well as file permissions are too open. Group *rw* is unnecessary and might present a security risk. 

Such files on a Linux system fail the *CIS Ubuntu 16.04 LTS Hardening Requirements* check no. *6.1.10 Ensure no world writable files exist (Scored)* therefore we consider this type of file creation process a security threat.

The executed command **dotnet restore** does not respect the umask set (either system-wide or per current bash session).

Similar issue was reported last year (https://github.com/NuGet/Home/issues/7673) which resulted in the CVE being published for it.

**Comment by danmosemsft** [comment]
Can you help figure out where this should go?

cc @blowdart

**Comment by blowdart** [comment]
This should have been fixed as part of https://github.com/NuGet/Home/issues/7673 I would have thought.

So whoever owns dotnet restore needs to own this, I don't know who that is.

**Comment by marcpopMSFT** [comment]
@aortiz-msft @nkolev92 there's an internal report of something very similar to this still happening. Can ya'll engage with @dsplaisted who is on the chat about it?

**Comment by nbennke** [comment]
Any plans on changes here? What about automatically adding sticky bits to the folders?

**Comment by KalleOlaviNiemitalo** [comment]
<https://github.com/dotnet/runtime/pull/112213> has been merged; the Mutex constructor supporting NamedWaitHandleOptions.CurrentUserOnly will be in .NET 10.

PSReadLine could perhaps use the new API at <https://github.com/PowerShell/PSReadLine/blob/5863e8d81cc28a13fa6798cd77bb43d472d05f5e/PSReadLine/Options.cs#L129>, but there are difficulties:

- PSReadLine is targeting `netstandard2.0`, which does not have this API.  It would need to multitarget or call the API by reflection.
- If the same user is running PSReadLine on multiple versions of PowerShell on different frameworks, and only the version on .NET 10 uses NamedWaitHandleOptions.CurrentUserOnly, then they create separate mutexes, and access to the history file is not properly serialised.
  * On Linux, PSReadLine could define an opt-in switch to enable the new API.  Users would be able to turn this on if they know that they aren't using PSReadLine on lower versions of .NET.  After support for .NET 8 has ended and .NET 10 has become the lowest supported framework, a new version of PSReadLine could turn the switch on by default.  This assumes users who run multiple versions of PowerShell in parallel are at least using the same version of PSReadLine on all of them.
  * On Windows, the user may also be using Windows PowerShell 5.1 on .NET Framework, which Microsoft may still keep supporting for a long time.  So the compatibility switch could never be enabled by default, unless PSReadLine ports the .NET 10 Mutex code to Platform Invoke on .NET Framework.

The migration looks quite messy overall.

On Windows, I wonder whether the CreateBoundaryDescriptor, AddSIDToBoundaryDescriptor, and CreatePrivateNamespace functions were considered for preventing squatting on the names of per-user  synchronisation objects.
