### ISSUE TITLE
dotnet pack fails because is seems to be trying to pack the assembly before it has been build

### ISSUE THREAD

**Issue by robertpi** [dotnet/sdk#13557]
I have a .sln file and and some SDK style csproj files. I build with the command:

```
dotnet.EXE  pack "D:\a\AgentDotnet\AgentDotnet\AgentDotnet\src\Agent\Sqreen.Agent.sln" --configuration Release --output "D:\a\AgentDotnet\AgentDotnet\AgentDotnet\build\agent" /nodeReuse:False /clp:ForceConsoleColor "/bl:C:\Users\runneradmin\AppData\Local\Temp\tmp61E0.tmp.binlog"
```

I can build them locally without issue, but when I try and build them on a github action the build fails with the error:

```
PackTask: C:\hostedtoolcache\windows\dncs\3.1.301\x64\sdk\3.1.301\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(198,5): error NU5026: The file 'D:\a\AgentDotnet\AgentDotnet\AgentDotnet\src\Agent\Sqreen.Agent.Extensions\bin\Release\net45\Sqreen.Agent.Extensions.dll' to be packed was not found on disk.
```

This seems to be a bug because the log from the build server shows error occurs before the .dll is build and the .dll is build successfully a few moments later. I've run the build several times and it also fails on the same .dll. 

Locally I'm using ```Microsoft (R) Build Engine version 16.7.0-preview-20360-03+188921e2f for .NET``` but the github vm image is installed with ```Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Core```.

This is the full log from the github action build server:

```
2020-09-12T05:00:58.2019296Z Starting task 'DotNet:pack': D:\a\AgentDotnet\AgentDotnet\AgentDotnet\src\Agent\Sqreen.Agent.sln
2020-09-12T05:00:58.4066636Z D:\a\AgentDotnet\AgentDotnet\AgentDotnet> "C:\hostedtoolcache\windows\dncs\3.1.301\x64\dotnet.EXE"  msbuild /version /nologo (In: false, Out: true, Err: true)
2020-09-12T05:00:58.7785626Z 16.6.0.22303
2020-09-12T05:00:58.7889333Z D:\a\AgentDotnet\AgentDotnet\AgentDotnet> "C:\hostedtoolcache\windows\dncs\3.1.301\x64\dotnet.EXE"  pack "D:\a\AgentDotnet\AgentDotnet\AgentDotnet\src\Agent\Sqreen.Agent.sln" --configuration Release --output "D:\a\AgentDotnet\AgentDotnet\AgentDotnet\build\agent" /nodeReuse:False /clp:ForceConsoleColor "/bl:C:\Users\runneradmin\AppData\Local\Temp\tmp61E0.tmp.binlog" (In: false, Out: false, Err: false)
2020-09-12T05:00:59.1643407Z Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Core
2020-09-12T05:00:59.1652062Z Copyright (C) Microsoft Corporation. All rights reserved.
2020-09-12T05:00:59.1652679Z 
2020-09-12T05:00:59.2277259Z C:\hostedtoolcache\windows\dncs\3.1.301\x64\sdk\3.1.301\MSBuild.dll -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\hostedtoolcache\windows\dncs\3.1.301\x64\sdk\3.1.301\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\hostedtoolcache\windows\dncs\3.1.301\x64\sdk\3.1.301\dotnet.dll -maxcpucount -property:Configuration=Release -property:PackageOutputPath=D:\a\AgentDotnet\AgentDotnet\AgentDotnet\build\agent -restore -target:pack -verbosity:m /bl:C:\Users\runneradmin\AppData\Local\Temp\tmp61E0.tmp.binlog /clp:ForceConsoleColor /nodeReuse:False D:\a\AgentDotnet\AgentDotnet\AgentDotnet\src\Agent\Sqreen.Agent.sln
2020-09-12T05:01:00.3322102Z   Determining projects to restore...
2020-09-12T05:01:01.3176004Z   Restored D:\a\AgentDotnet\AgentDotnet\AgentDotnet\src\Agent\Microsoft.Diagnostics.Tools.RuntimeClient\Microsoft.Diagnostics.Tools.RuntimeClient.csproj (in 614 ms).
2020-09-12T05:01:03.9606066Z   Restored D:\a\AgentDotnet\AgentDotnet\AgentDotnet\src\Agent\Extensions\Mvc3\Mvc3.csproj (in 3.2 sec).
2020-09-12T05:01:03.9609925Z   Restored D:\a\AgentDotnet\AgentDotnet\AgentDotnet\src\Agent\Extensions\Asp35\Asp35.csproj (in 7 ms).
2020-09-12T05:01:05.3942726Z   Restored D:\a\AgentDotnet\AgentDotnet\AgentDotnet\src\Agent\Sqreen.Core\Sqreen.Core.csproj (in 1.42 sec).
2020-09-12T05:01:06.2057540Z   Restored D:\a\AgentDotnet\AgentDotnet\AgentDotnet\src\Agent\Sqreen.Api.Agent\Sqreen.Api.Agent.csproj (in 811 ms).
2020-09-12T05:01:07.6461726Z   Restored D:\a\AgentDotnet\AgentDotnet\AgentDotnet\src\Agent\Sqreen.Agent.Extensions\Sqreen.Agent.Extensions.csproj (in 1.42 sec).
2020-09-12T05:01:24.4297007Z   Restored D:\a\AgentDotnet\AgentDotnet\AgentDotnet\src\Agent\Sqreen.Agent.Core\Sqreen.Agent.Core.csproj (in 13.71 sec).
2020-09-12T05:01:30.3335285Z   Restored D:\a\AgentDotnet\AgentDotnet\AgentDotnet\src\Agent\Extensions\AspNetCore\AspNetCore.csproj (in 29.01 sec).
2020-09-12T05:01:31.9456492Z ##[error][31;1mC:\hostedtoolcache\windows\dncs\3.1.301\x64\sdk\3.1.301\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(198,5): error NU5026: The file 'D:\a\AgentDotnet\AgentDotnet\AgentDotnet\src\Agent\Sqreen.Agent.Extensions\bin\Release\net45\Sqreen.Agent.Extensions.dll' to be packed was not found on disk. [D:\a\AgentDotnet\AgentDotnet\AgentDotnet\src\Agent\Sqreen.Agent.Extensions\Sqreen.Agent.Extensions.csproj]
2020-09-12T05:01:32.3720210Z [m  Sqreen.Api.Agent -> D:\a\AgentDotnet\AgentDotnet\AgentDotnet\src\Agent\Sqreen.Api.Agent\bin\Release\net45\Sqreen.Api.Agent.dll
2020-09-12T05:01:32.3723345Z   Sqreen.Api.Agent -> D:\a\AgentDotnet\AgentDotnet\AgentDotnet\src\Agent\Sqreen.Api.Agent\bin\Release\netstandard2.0\Sqreen.Api.Agent.dll
2020-09-12T05:01:33.0968284Z   Sqreen.Agent.Extensions -> D:\a\AgentDotnet\AgentDotnet\AgentDotnet\src\Agent\Sqreen.Agent.Extensions\bin\Release\net45\Sqreen.Agent.Extensions.dll
2020-09-12T05:01:33.1351676Z   Sqreen.Agent.Extensions -> D:\a\AgentDotnet\AgentDotnet\AgentDotnet\src\Agent\Sqreen.Agent.Extensions\bin\Release\netstandard2.0\Sqreen.Agent.Extensions.dll
2020-09-12T05:01:33.4783183Z   Sqreen.Core -> D:\a\AgentDotnet\AgentDotnet\AgentDotnet\src\Agent\Sqreen.Core\bin\Release\netstandard2.0\Sqreen.Core.dll
2020-09-12T05:01:33.8826697Z   Sqreen.Core -> D:\a\AgentDotnet\AgentDotnet\AgentDotnet\src\Agent\Sqreen.Core\bin\Release\net45\Sqreen.Core.dll
2020-09-12T05:01:33.9577436Z   Microsoft.Diagnostics.Tools.RuntimeClient -> D:\a\AgentDotnet\AgentDotnet\AgentDotnet\src\Agent\Microsoft.Diagnostics.Tools.RuntimeClient\bin\Release\netstandard2.0\Microsoft.Diagnostics.Tools.RuntimeClient.dll
2020-09-12T05:01:34.9984913Z   Sqreen.Agent.Core -> D:\a\AgentDotnet\AgentDotnet\AgentDotnet\src\Agent\Sqreen.Agent.Core\bin\Release\netstandard2.0\Sqreen.Agent.Core.dll
2020-09-12T05:01:35.5347203Z   AspNetCore -> D:\a\AgentDotnet\AgentDotnet\AgentDotnet\src\Agent\Extensions\AspNetCore\bin\Release\netstandard2.0\Sqreen.Providers.Wrapper.AspNetCore.dll
2020-09-12T05:01:36.2629659Z   Sqreen.Agent.Core -> D:\a\AgentDotnet\AgentDotnet\AgentDotnet\src\Agent\Sqreen.Agent.Core\bin\Release\net45\Sqreen.Agent.Core.dll
2020-09-12T05:01:36.8695508Z   Asp35 -> D:\a\AgentDotnet\AgentDotnet\AgentDotnet\src\Agent\Extensions\Asp35\bin\Release\net45\Sqreen.Providers.Wrapper.Asp35.dll
2020-09-12T05:01:36.9045429Z   Mvc3 -> D:\a\AgentDotnet\AgentDotnet\AgentDotnet\src\Agent\Extensions\Mvc3\bin\Release\net45\Sqreen.Providers.Wrapper.Mvc3.dll
2020-09-12T05:01:36.9154687Z   Successfully created package 'D:\a\AgentDotnet\AgentDotnet\AgentDotnet\build\agent\Microsoft.Diagnostics.Tools.RuntimeClient.1.0.0.nupkg'.
2020-09-12T05:01:36.9185247Z   Successfully created package 'D:\a\AgentDotnet\AgentDotnet\AgentDotnet\build\agent\Sqreen.Agent.Core.1.0.0.nupkg'.
2020-09-12T05:01:36.9194622Z   Successfully created package 'D:\a\AgentDotnet\AgentDotnet\AgentDotnet\build\agent\Sqreen.Providers.Wrapper.AspNetCore.1.0.0.nupkg'.
2020-09-12T05:01:36.9207716Z   Successfully created package 'D:\a\AgentDotnet\AgentDotnet\AgentDotnet\build\agent\Sqreen.Providers.Wrapper.Asp35.1.0.0.nupkg'.
2020-09-12T05:01:36.9234833Z   Successfully created package 'D:\a\AgentDotnet\AgentDotnet\AgentDotnet\build\agent\Sqreen.Core.1.0.0.nupkg'.
2020-09-12T05:01:36.9583421Z   Successfully created package 'D:\a\AgentDotnet\AgentDotnet\AgentDotnet\build\agent\Sqreen.Api.Agent.1.0.0.nupkg'.
2020-09-12T05:01:36.9609152Z   Successfully created package 'D:\a\AgentDotnet\AgentDotnet\AgentDotnet\build\agent\Sqreen.Providers.Wrapper.Mvc3.1.0.0.nupkg'.
2020-09-12T05:01:49.7260901Z PackTask: C:\hostedtoolcache\windows\dncs\3.1.301\x64\sdk\3.1.301\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(198,5): error NU5026: The file 'D:\a\AgentDotnet\AgentDotnet\AgentDotnet\src\Agent\Sqreen.Agent.Extensions\bin\Release\net45\Sqreen.Agent.Extensions.dll' to be packed was not found on disk.
2020-09-12T05:01:49.7283607Z Finished (Failed) 'DotNet:pack' in 00:00:51.5258881
```

**Comment by sfoslund** [comment]
Have you tried updating to use a more recent version of MSBuild on the image? Given it works with a newer version locally, it might be a bug that was fixed in subsequent versions.

**Comment by robertpi** [comment]
Yes, just change my github action to use SDK 3.1.402, which comes with msbuild 16.7.0.41201 and I'm still seeing the same issue.

I'm using SDK 3.1.402 and msbuild locally 16.7.0.41201 and it works well.

**Comment by sfoslund** [comment]
If the same command is having different behavior on GitHub actions than it does locally, it must be a problem with the pipeline. I would suggest filing an issue with the actions team, maybe this repo: https://github.com/actions/setup-dotnet
