### ISSUE TITLE
MSBuild target Pack fails - System.IO.Compression 4.1.0 not found

### ISSUE THREAD

**Issue by jp2masa** [dotnet/sdk#1384]
I'm using .NET Core 2.0 Preview 2 (2.0.0-preview2-006497) and when running MSBuild (from the Visual Studio installation) with targets Restore and Pack the operation fails with the following error message:
> C:\Program Files\dotnet\sdk\2.0.0-preview2-006497\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(141,5): error : Could not load file or assembly 'System.IO.Compression, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.

The project is targeting netstandard1.5 and adding global.json with sdk version "1.0.4" works fine.

**Comment by livarcocc** [comment]
Are you invoking pack through msbuild or through the CLI?

**Comment by jp2masa** [comment]
MSBuild, from the Visual Studio installation folder.

**Comment by rainersigwald** [comment]
May be related to https://github.com/Microsoft/msbuild/pull/2235, which adds a binding redirect for that assembly (so we should never try to load 4.1.0.0, only the version that we ship).

**Comment by jp2masa** [comment]
I'm using the latest Visual Studio Preview, which includes the latest MSBuild version, right? The latest release was 8 days ago and that fix was merged 14 days ago, so it should be working.

**Comment by rainersigwald** [comment]
@jp2masa that change isn't in the latest public preview--it takes some time for changes in the MSBuild repo to flow into the VS release. You could try manually applying the `msbuild.exe.config` change on your machine to confirm that it's fixed by that problem, or wait for the next public preview.

**Comment by jp2masa** [comment]
I applied the change in MSBuild.exe.config, but it's still not finding the assembly. I confirmed the assembly signature of the System.IO.Compression.dll file in the MSBuild folder, and the signature is equal to the one being searched by MSBuild after the change.

**Comment by jp2masa** [comment]
What is strange is that using the same MSBuild with dotnet sdk 1.0.4 specified in global.json it works.

**Comment by rainersigwald** [comment]
Crosslinking to https://github.com/NuGet/Home/issues/4290.

**Comment by jp2masa** [comment]
This seems to be fixed in the latest Visual Studio Preview version.
