### ISSUE TITLE
Single-file publish includes unnecessary files in the output

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/sdk#16487]
Repro:
```console
dotnet new console
dotnet publish -r win-x64 /p:PublishSingleFile=true
```

The output directory should contain the `app.exe`, `app.pdb` and maybe a couple of debugger support files. Currently it has 57 files, including `coreclr.dll` and so on. These files are also listed in the `.deps.json` which is baked into the bundle, so the app won't start without them.

But it doesn't need those files - replacing coreclr.dll with an empty file of the same name - the app works just fine.

**Comment by vitek-karas** [comment]
@VSadov @eerhardt @agocke

**Comment by am11** [comment]
Reproducible in preview 3 and 4.
As part of the fix - a unit test that publishes the template console app to a new dir and asserts on count of files in the publish directory be _exactly_ `2` (app and app.pdb), would go a long way to avoid such regressions in the future.

**Comment by agocke** [comment]
@VSadov could you look at this? I created a test for it at https://github.com/dotnet/sdk/pull/16745 but it looks like the problem is that the SDK looks at the runtime pack manifest to decide whether to exclude the content from single-file publishing, and it looks like a lot of the code for generating that manifest was removed in your refactoring.

**Comment by VSadov** [comment]
I will take a look.

**Comment by ThomasGoulet73** [comment]
I was looking for a temporary workaround and I think I found the source of the problem but I don't know how to fix it.

The attribute `DropFromSingleFile` is no longer added in the file `RuntimeList.xml`. I copied the `RuntimeList.xml` from preview 2 in `C:\Users\{User}\.nuget\packages\microsoft.netcore.app.runtime.win-x86\6.0.0-preview.3.21201.4\data` and changed the file version and it worked. The only dll remaining is mscordaccore.dll.

**Comment by VSadov** [comment]
@ThomasGoulet73  Yes, there was a regression related to `DropFromSingleFile`. Copying old `RuntimeList.xml` could be enough as a temporary workaround. 
`mscordaccore.dll` should not be needed either. You may try to tweak your `RuntimeList.xml` to drop it too.

**Comment by VSadov** [comment]
fixed in https://github.com/dotnet/runtime/pull/51030

**Comment by agocke** [comment]
Looks like there hasn't been a merge between runtime and SDK yet, so this test is still failing https://github.com/dotnet/sdk/pull/16745

I don't think this is resolved until that test starts passing.

**Comment by VSadov** [comment]
Right, I keep forgetting that the fix was in runtime.

**Comment by am11** [comment]
Thanks a lot for a quick fix.
Runtime update is currently blocked on https://github.com/dotnet/sdk/pull/16810.

**Comment by am11** [comment]
All related PRs merged and SDK propagated to installer. This is fixed in the latest preview4 build. 👍

```sh
$ dotnet --version
6.0.100-preview.4.21216.18

$ dotnet new console -n myapp1

$ dotnet publish myapp1 -c Release --use-current-runtime \
    -p:'SelfContained=true;PublishSingleFile=true' -o /tmp/mypublishdir

$ ls /tmp/mypublishdir
myapp1  myapp1.pdb
```
