### ISSUE TITLE
`dotnet tool install --interactive` times out with .NET 6 preview SDK

### ISSUE THREAD

**Issue by BillWagner** [dotnet/sdk#18615]
I ran the following command to install one of our docs internal tools on a new machine:

```cli
dotnet tool update dotnet-whatsnew -g --add-source https://pkgs.dev.azure.com/mseng/TechnicalContent/_packaging/DotnetDocsTools%40Local/nuget/v3/index.json --interactive
```

On the new Mac, where the .NET 6 Preview SDK was installed, the command never prompted me for the keys from the Azure Artifacts Credential Provider.

To work around the issue, I created a global.json that pinned the CLI to the .NET 5 SDK.

**Comment by Dan-Albrecht** [comment]
Hitting the same thing on 6.0.100-preview.6.21355.2. Manually targeting SDK 5 worked around the issue.

**Comment by sfoslund** [comment]
Closing as a dup of https://github.com/dotnet/sdk/issues/21802, which was fixed by #22251

**Comment by RemyBoyer** [comment]
Hello @sfoslund 

I'm still having this issue, even if I'm now using the sdk `6.0.200`. Am I missing something?

```powershell
PS> iex "& { $(irm https://aka.ms/install-artifacts-credprovider.ps1) }"
Fetching release https://api.github.com/repos/Microsoft/artifacts-credprovider/releases/latest

    Directory: C:\Users\RémyBOYER\AppData\Local\Temp

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          21/02/2022    09:21                CredProviderZip
Downloading https://github.com/microsoft/artifacts-credprovider/releases/download/v0.1.28/Microsoft.NetCore2.NuGet.CredentialProvider.zip to C:\Users\RémyBOYER\AppData\Local\Temp\CredProviderZip\Microsoft.NetCore2.NuGet.CredentialProvider.zip
Extracting zip to the Credential Provider temp directory C:\Users\RémyBOYER\AppData\Local\Temp\CredProviderZip
Credential Provider installed successfully

PS>  dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.200
 Commit:    4c30de7899

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.200\

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

.NET SDKs installed:
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.416 [C:\Program Files\dotnet\sdk]
  5.0.405 [C:\Program Files\dotnet\sdk]
  6.0.200 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

PS> dotnet tool install yuc-aad -g --add-source https://pkgs.dev.azure.com/<redacted>/_packaging/release/nuget/v3/index.json --interactive
C:\Program Files\dotnet\sdk\6.0.200\NuGet.targets(130,5): error :     [CredentialProvider]Device flow authentication failed. User was presented with device flow, but didn't react within 90 seconds. [C:\Users\RémyBOYER\AppData\Local\Temp\jcqzge0p.iak\restore.csproj]
C:\Program Files\dotnet\sdk\6.0.200\NuGet.targets(130,5): error : Unable to load the service index for source https://pkgs.dev.azure.com/<redacted>/_packaging/release/nuget/v3/index.json. [C:\Users\RémyBOYER\AppData\Local\Temp\jcqzge0p.iak\restore.csproj]
C:\Program Files\dotnet\sdk\6.0.200\NuGet.targets(130,5): error :   Response status code does not indicate success: 401 (Unauthorized). [C:\Users\RémyBOYER\AppData\Local\Temp\jcqzge0p.iak\restore.csproj]
The tool package could not be restored.
Tool 'yuc-aad' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
```

Thanks for your help!

**Comment by RemyBoyer** [comment]
FYI, the issue has disappeared with the sdk `6.0.201` :+1:
