### ISSUE TITLE
Some CLI commands don't respect DOTNET_CLI_UI_LANGUAGE

### ISSUE THREAD

**Issue by HymanZHAN** [dotnet/sdk#21159]
### Describe the bug
I've set the `DOTNET_CLI_UI_LANGUAGE` env variable to `en-us`, and `dotnet --info` is displaying in English. However, some commands like `dotnet restore` still "speaks" Chinese, which is the language of my local machine.

### To Reproduce

1. Create an class library using `dotnet new classlib -n Infrastructure`
2. View the output:
```sh
> dotnet new classlib -n Infrastructure
The template "Class library" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on Infrastructure\Infrastructure.csproj...
  正在确定要还原的项目…
  所有项目均是最新的，无法还原。
Restore succeeded.
```

### Exceptions (if any)

The info should all be in English.

### Further technical details
- Include the output of `dotnet --info`

```sh
.NET SDK (reflecting any global.json):
 Version:   5.0.302
 Commit:    c005824e35

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.302\

Host (useful for support):
  Version: 6.0.0-preview.7.21377.19
  Commit:  91ba01788d

.NET SDKs installed:
  5.0.202 [C:\Program Files\dotnet\sdk]
  5.0.300 [C:\Program Files\dotnet\sdk]
  5.0.302 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]     
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.7.21378.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

VS Code 1.60.1

**Remarks**:
I have a global.json to pin the dotnet version used.

```json
{
  "sdk": {
    "version": "5.0.302"
  }
}
```

**Comment by marcpopMSFT** [comment]
Doesn't repro for me in 5.0.4xx or newer but does in 5.0.2xx so I wonder if this got fixed at some point.  Can you see if it happens with a newer SDK than 5.0.302?

**Comment by HymanZHAN** [comment]
Nope. 5.0.401 still doesn't work for me. I can try if rebooting the machine helps later, but my expectation is low.

```shell
Development/Projects/LocalTest2 via •NET v5.0.401
> echo $env:DOTNET_CLI_UI_LANGUAGE
en-us

Development/Projects/LocalTest2 via •NET v5.0.401
> dotnet --version
5.0.401

Development/Projects/LocalTest2 via •NET v5.0.401
> dotnet new classlib -o Lib1
The template "Class library" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on Lib1\Lib1.csproj...
  正在确定要还原的项目…
  已还原 C:\Users\zhanx\Development\Projects\LocalTest2\Lib1\Lib1.csproj (用时 67 ms)。
Restore succeeded.
```
Is the `DOTNET_CLI_UI_LANGUAGE` the only configurable place?

**Comment by marcpopMSFT** [comment]
DOTNET_CLI_UI_LANGUAGE is the only way to configure this in the sdk. Those strings come from nuget but should respect the same value.  @aortiz-msft @JonDouglas any way to investigate why nuget wouldn't be matching the SDK language?
