### ISSUE TITLE
SDK 6.0.301 -> 6.0.302 upgrade breaks our build

### ISSUE THREAD

**Issue by AArnott** [dotnet/sdk#26557]
### Describe the bug

The [VS-Platform repo](https://devdiv@dev.azure.com/devdiv/DevDiv/_git/_optimized/VS-Platform) build broke when the .NET SDK version installed on local dev boxes went from 6.0.301 to 6.0.302 (which released yesterday). Some kind of breaking change was made in this version of the SDK.

### To Reproduce

On a machine with 6.0.301 or 6.0.302 installed

```
git clone https://devdiv@dev.azure.com/devdiv/DevDiv/_git/_optimized/VS-Platform
cd VS-Platform
git checkout 359c6d2f1db9b1adc15b11262aaf74ac625af938
.\init -Feature Editor
msbuild /t:rebuild src\Editor\VisualStudio\Impl\EditorImpl.csproj /r
```

If 6.0.302 is present, you'll see a bunch of build errors around the CsWin32 source generator we use, such as:

> C:\Users\andarno\source\repos\VS-Platform\src\Editor\VisualStudio\Impl\Microsoft.Windows.CsWin32\Microsoft.Windows.CsWin32.SourceGenerator\Windows.Win32.PInvoke.User32.g.cs(331,52): error CS0111: Type 'PInvoke' already defines a member called 'SetWindowPos' with the same parameter types [C:\Users\andarno\source\repos\VS-Platform\src\Editor\VisualStudio\Impl\EditorImpl_jqjdp0fp_wpftmp.csproj]

But with 6.0.300 or 6.0.301, the build succeeds.

### Further technical details

VS 17.4 Preview 1 (32711.401.main) is installed and where the msbuild.exe used in the repro steps comes from.

**Comment by chsienki** [comment]
https://github.com/dotnet/sdk/issues/26542

**Comment by marcpopMSFT** [comment]
This is the issue tracking the fix. https://github.com/dotnet/wpf/issues/6792

**Comment by JochemPalmsens** [comment]
@chsienki is it a dupe? I'm not using wpf or CommunityToolkit.MVVC but still go problems when upgrading to VS 17.2.6 yesterday. I made a [dev community issue](https://developercommunity.visualstudio.com/t/Visual-studio-1726-intellisense-is-bro/10094332)

To summerize that: 
- After the update the build broke
- After a full reinstall of 17.2.6 the build worked again, but intellisense was broken for test and utility projects (cannot find analyzers)
- after manually opening all the problematic projects, the analyzer paths were (automatically) fixed and I could work again

This cost me the better half of my working day yesterday, which was very inconvenient.

Note, I am developing w WinUI3 app, so maybe CommunityToolkit.WinUI.UI.Controls gave similar issue?

**Comment by kipusoep** [comment]
@JochemPalmsens yeah the root issue is the same.
I was able to fix it using these instructions: https://github.com/dotnet/wpf/issues/6792#issuecomment-1183530305

**Comment by AArnott** [comment]
This did _not_ get fixed in 6.0.303 or 6.0.400. Sorely disappointing given how broken source generators are by this regression and we waited a month for the fix and it didn't come. What's going on?

**Comment by Dragnalith** [comment]
I confirm I also experience this issue with 6.0.303, and I have just tried 6.0.400 which does not fix it on my side either.

**Comment by AArnott** [comment]
This is expected to be fixed this month (second Tuesday) in 6.0.304 and 6.0.401.

**Comment by AhmedZero** [comment]
I think it fixed now.

**Comment by AArnott** [comment]
I just tried 6.0.401 today and it does appear to in fact fix the problem!
