### ISSUE TITLE
dotnet format fails to locate msbuild

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/sdk#27332]
Running `dotnet format` on a recent build from main fails with

```
Unable to locate MSBuild. Ensure the .NET SDK was installed with the official installer.
```

This is a regression source-build tests caught.  I was able to reproduce this with the Microsoft build as well.

This last passed CI on https://github.com/dotnet/installer/commit/319773e868fead7c3bedba92f894594d1d81ff59. There were a few commits after that before the next failing CI run on https://github.com/dotnet/installer/commit/d117d579c56308c490d40e0860b6c926c08d5ae3.

Related to https://github.com/dotnet/source-build/issues/3004

**Comment by MichaelSimons** [comment]
cc @marcpopMSFT - I wasn't sure where to log this.  Please move as appropriate.

**Comment by marcpopMSFT** [comment]
CC @jmarolf @JoeRobich for dotnet format.

@MichaelSimons see https://github.com/dotnet/sdk/blob/d194ac295528af5f9b6ffafc335435ef89efed21/CODEOWNERS#L29

**Comment by JoeRobich** [comment]
Interesting. dotnet-format uses MSBuildLocator to find MSBuild. We have discussed moving to relative path, since we know the layout of the SDK folder in advance. I will take a look and see what I can find out.

**Comment by JoeRobich** [comment]
The failing build has changes to move the Major version to 8.0. This check in MSBuildLocator appears to only return MSBuild instance which are from SDKs whose version is equal to or less than the Runtime (https://github.com/microsoft/MSBuildLocator/blob/850d27b4ff8253d017ae4968154febc33c1db529/src/MSBuildLocator/DotNetSdkLocationHelper.cs#L54-L62). I believe the check is causing the locator to discard the 8.0 SDK and return no instances of MSBuild. I believe dotnet-format should make it a priority to load MSBuild by relative path when executing from the dotnet CLI to avoid this situation.

**Comment by marcpopMSFT** [comment]
If that's the case, this iwll resolve itself once our various branding/codeflow changes for 8.0 are completed. We're not quite there yet.

**Comment by badsyntax** [comment]
Can anyone suggest any workarounds? This is causing me anguish as we rely on `dotnet format` in our team.

I've tried:

- removing `~/global.json`
- remove all sdks and runtimes
- reinstall `7.0.101` (sdk's and runtime versions match)

I don't understand why using a (sightly older) version of .net7 doesn't work, but tbh I don't really understand the source of the issue. Any suggestions would be greatly appreciated. What am I doing wrong?

**Comment by marcpopMSFT** [comment]
This issue is about .NET 8 and should be resolved now. @badsyntax you should file a new issue in the dotnet format repo with the details including which SDK versions you're using.

**Comment by vmandic** [comment]
How is this resolved, any links to solution please? I am still facing it with alpine docker image.
