### ISSUE TITLE
dotnet workload install always displays "The machine has a pending reboot. Installation will continue, but you may need to restart."

### ISSUE THREAD

**Issue by groogiam** [dotnet/sdk#28993]
### Describe the bug
On both Windows 10 and 11 `dotnet workload install` always shows The machine has a pending reboot. Installation will continue, but you may need to restart.

This message does not go away even after restart and windows update is not showing an pending installs.

### To Reproduce
Run the following command
`dotnet workload install wasm-tools`

### Further technical details
- Include the output of `dotnet --info`
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  6.0.306 [C:\Program Files\dotnet\sdk]
  7.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by nagilson** [comment]
I'm pretty sure this was fixed between rc-1 and RTM, as it doesn't occur for me anymore on RTM but does occur on RC1. 
https://github.com/dotnet/sdk/pull/27095 Seems like it was this commit, thanks @joeloff !

**Comment by groogiam** [comment]
@nagilson This does not appear to be fixed. It is still happening on both my desktop (Windows 10) and laptop (windows 11). Both of these have the 7.0 RTM SDK installed (see output from dotnet info in the original post).

![image](https://user-images.githubusercontent.com/1992395/202080356-b762d55e-8fb8-41be-8812-7f76f525bd2b.png)

![image](https://user-images.githubusercontent.com/1992395/202080502-91e1be20-4017-4103-aed3-07657f2e6dff.png)

**Comment by joeloff** [comment]
@groogiam can you try the following registry queries?

- `reg query "hklm\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired"`
- `reg query "SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\RebootPending"`
- `reg query "hklm\SYSTEM\CurrentControlSet\Control\Session Manager" /v PendingFileRenameOperations`

**Comment by groogiam** [comment]
```shell
C:\Windows\system32>reg query "hklm\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired"
ERROR: The system was unable to find the specified registry key or value.

C:\Windows\system32>reg query "SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\RebootPending"
ERROR: Invalid key name.
Type "REG QUERY /?" for usage.

C:\Windows\system32>reg query "hklm\SYSTEM\CurrentControlSet\Control\Session Manager" /v PendingFileRenameOperations


ERROR: The system was unable to find the specified registry key or value.

C:\Windows\system32>
```

**Comment by nagilson** [comment]
The middle key was missing hklm, `reg query "hklm\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\RebootPending"`. Thanks for the fast response and following up!

**Comment by groogiam** [comment]
```shell
C:\Windows\system32>reg query "hklm\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\RebootPending"
ERROR: The system was unable to find the specified registry key or value.
```

**Comment by nagilson** [comment]
We've dug into this some more and this behavior is really peculiar. _Theoretically_ if those registry keys aren't set, the reboot code should never trigger. It's possible there (was) a program aggressively renaming temporary files on your machine.

@groogiam 
There are workload log files that may help us further, you can find all of them by doing `dir %temp%\Microsoft.NET.Workload*.log`.
May you please find the log with the corresponding timestamp to when you encounter(ed) this problem, and you do 1 of the following?

1) Look for `RebootPending` at the top of the log, it will be something like:
```
[2022-11-14 10:02:18.139] [00000000] Is64BitProcess: True
[2022-11-14 10:02:18.139] [00000000] RebootPending: False
```
and send us the value?

<OR>

2) Attach the log(s) but be sure to remove any personal information, https://privacy.microsoft.com/en-US/privacystatement. The top is preferred.

**Comment by groogiam** [comment]
Here is the top of the log.

```
[2022-11-19 00:59:31.102] [000056D8] === Logging started ===
[2022-11-19 00:59:31.110] [000056D8] Executing: dotnet  workload install wasm-tools, PID: 22232, PPID: 172
[2022-11-19 00:59:31.111] [000056D8] IsElevated: False
[2022-11-19 00:59:31.111] [000056D8] Is64BitProcess: True
[2022-11-19 00:59:31.111] [000056D8] RebootPending: True
[2022-11-19 00:59:31.111] [000056D8] ProcessorArchitecture: amd64
[2022-11-19 00:59:31.111] [000056D8] HostArchitecture: x64
[2022-11-19 00:59:31.111] [000056D8] SdkDirectory: 7.0.100
[2022-11-19 00:59:31.111] [000056D8] VerifySignatures: True
[2022-11-19 00:59:31.111] [000056D8] SDK feature band: 7.0.100
```

**Comment by donaldnevermore** [comment]
Same problem. Here is my log.
```
[2022-12-19 22:43:01.454] [000020F0] Executing: "c:\program files\dotnet\dotnet.exe" workload install wasm-experimental, PID: 8432, PPID: 12244
[2022-12-19 22:43:01.457] [000020F0] IsElevated: True
[2022-12-19 22:43:01.458] [000020F0] Is64BitProcess: True
[2022-12-19 22:43:01.458] [000020F0] RebootPending: True
[2022-12-19 22:43:01.458] [000020F0] ProcessorArchitecture: amd64
[2022-12-19 22:43:01.458] [000020F0] HostArchitecture: x64
[2022-12-19 22:43:01.458] [000020F0] SdkDirectory: 7.0.101
[2022-12-19 22:43:01.458] [000020F0] VerifySignatures: True
[2022-12-19 22:43:01.458] [000020F0] SDK feature band: 7.0.100
[2022-12-19 22:43:01.458] [000020F0] wuauserv, status: Stopped, can stop: False
```

**Comment by nagilson** [comment]
Sorry to have gone quiet on this. I appreciate your cooperation and really want to get it fixed because you've been great to work with. Not expecting movement on this for a bit, but wanted to say it's still on our radar.

**Comment by matt-goldman** [comment]
I've just encountered this issue too, although I do show a registry result for the third entry:
```
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager
    PendingFileRenameOperations    REG_MULTI_SZ    \??\C:\ProgramData\Microsoft\VisualStudio\Packages\_bootstrapper\vs_setup_bootstrapper_202301112011054198.json\0\??\C:\Users\mattg\AppData\Local\Temp\DEL3DF.tmp\0\??\C:\Users\mattg\AppData\Local\Temp\DEL3EF.tmp\0\??\C:\Users\mattg\AppData\Local\Temp\DEL3F0.tmp
```
   
Should I delete those files, and/or the registry entry?

**Comment by nagilson** [comment]
Noooo, you definitely shouldn't, that is a pending file rename managed by VS. Doing that may destabilize VS.

**Comment by matt-goldman** [comment]
Ok thanks, well...I actually went ahead and did it anyway. I was 100% blocked, my only other option was to format my machine and reinstall so I thought it was worth a last-ditch effort. Once I did that, I got a different error about the requested workloads not being in the manifest. So I deleted the manifest, then did a repair on Visual Studio. After that, I was able to successfully run `dotnet workload restore` and now everything is working.

**Comment by sellotape** [comment]
Got this as well.  Just to add what I saw (and eventual fix, in case others find it useful):

I had just tried a reboot anyway (even though nothing else indicated one was needed).  Same result after.

I ran the 3 scripts above; the last returned:
`reg query "hklm\SYSTEM\CurrentControlSet\Control\Session Manager" /v PendingFileRenameOperations`

```
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager
	PendingFileRenameOperations    REG_MULTI_SZ    \??\C:\Users\me\AppData\Local\Temp\da3a9f78-f318-43dc-b501-0bc8bbf2d8ec.tmp\0\??\C:\Users\me\AppData\Local\Temp\06482c31-11b0-4a14-ad6f-847164752608.tmp\0\??\C:\Program Files\Google\Chrome\Temp\scoped_dir16328_1967781880\old_chrome.exe\0\??\C:\Program Files\Google\Chrome\Temp\scoped_dir16328_1967781880\0\??\C:\Program Files\Google\Chrome\Temp\0\??\C:\Program Files\Google\Chrome\Temp\scoped_dir105592_1782936003\old_chrome.exe\0\??\C:\Program Files\Google\Chrome\Temp\scoped_dir105592_1782936003\0\??\C:\Program Files\Google\Chrome\Temp
```

Seems even though I'd just rebooted and Chrome had relaunched, it hadn't updated itself.  Unexpected.  I went to `Chrome > Help > About` and it updated.
The registry key remained, though, so I rebooted again (again no other indication to do so).

Reran `reg query "hklm\SYSTEM\CurrentControlSet\Control\Session Manager" /v PendingFileRenameOperations` and now nothing there.

Reran `dotnet workload restore` and it worked as expected this time.

Seems like it might be possible for dotnet to be more discerning in what it considers "reboot required" here?  E.g. a Chrome file-rename is almost certainly inconsequential to the outcome.
I suppose if it somewhere just asks the OS "any pending operations on reboot?" then fair enough, but this is a fairly less-than-optimal situation, especially as the user gets very little clue to reboot (and in this case reboot > dig around in registry settings > manually update Chrome > reboot).
