### ISSUE TITLE
Commands like `dotnet nuget push --help` do not give help, but forcing an error does

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/sdk#29048]
### Describe the bug
Trying to get help with `--help` often fails, or only dumps the available options, not the descriptions. For instance, `dotnet nuget push --help` shows:

```cmd
d:\Projects>dotnet nuget push --help
Description:

Usage:
  dotnet nuget push <package-paths>... [options]

Arguments:
  <package-paths>

Options:
  --force-english-output
  -s, --source <source>
  -ss, --symbol-source <symbol-source>
  -t, --timeout <timeout>
  -k, --api-key <api-key>
  -sk, --symbol-api-key <symbol-api-key>
  -d, --disable-buffering
  -n, --no-symbols
  --no-service-endpoint
  --interactive
  --skip-duplicate
  -?, -h, --help
```

Notice that the output itself says that `--help` is a valid option.

### To Reproduce
See above.

### Workaround
The somewhat unexpected workaround is to simply force help output by forcing a mistake. I.e., in this case, `dotnet nuget push --dummy` gives proper help:

```cmd
d:\Projects>dotnet nuget push --dummy
Specify --help for a list of available options and commands.
error: Unrecognized option '--dummy'


Usage: dotnet nuget push [arguments] [options]

Arguments:
  [root]  Specify the path to the package and your API key to push the package to the server.

Options:
  -h|--help                      Show help information
  --force-english-output         Forces the application to run using an invariant, English-based culture.
  -s|--source <source>           Package source (URL, UNC/folder path or package source name) to use. Defaults to DefaultPushSource if specified in NuGet.Config.
  -ss|--symbol-source <source>   Symbol server URL to use.
  -t|--timeout <timeout>         Timeout for pushing to a server in seconds. Defaults to 300 seconds (5 minutes).
  -k|--api-key <apiKey>          The API key for the server.
  -sk|--symbol-api-key <apiKey>  The API key for the symbol server.
  -d|--disable-buffering         Disable buffering when pushing to an HTTP(S) server to decrease memory usage.
  -n|--no-symbols                If a symbols package exists, it will not be pushed to a symbols server.
  --no-service-endpoint          Does not append "api/v2/package" to the source URL.
  --interactive                  Allow the command to block and require manual action for operations like authentication.
  --skip-duplicate               If a package and version already exists, skip it and continue with the next package in the push, if any.
```

**Comment by baronfel** [comment]
This sounds like something that would be resolved when the NuGet migration to System.CommandLine is complete. By default in that library descriptions are always emitted.

**Comment by ArwynFr** [comment]
Also, the output is misleadingly encouraging users to type their api key as an argument instead of an option.

**Comment by baronfel** [comment]
We've fixed this for nuget and a number of other tools in our CLI parsing code in the .NET 7 timeframe I believe.

**Comment by abelbraaksma** [comment]
Hmm. @baronfel this is still not working: `dotnet nuget push --help`, essentially gives the same output as in the OP, nothing on `push` specifically.

I tried to update NuGet itself, but that famous command doesn't work either anymore, it seems, though it is still shown in the [documentation](https://learn.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-update). I hope I'm just missing something obvious here due to long nights ;).

```
d:\projects>dotnet nuget update -self
Specify --help for a list of available options and commands.
error: Unrecognized option '-self'


Usage: dotnet nuget update [options] [command]

Options:
  -h|--help  Show help information

Commands:
  client-cert  Updates the client certificate configuration that matches the given package source name.
  source       Update a NuGet source.

Use "update [command] --help" for more information about a command.
```

**Comment by baronfel** [comment]
Self doesn't apply to the dotnet CLI version of nuget, only the standalone nuget.exe. nuget shipped in the dotnet CLI is only updateable as part of the overall .NET SDK.

**Comment by abelbraaksma** [comment]
I'm confused 😆

**Comment by abelbraaksma** [comment]
I just downloaded the commandline here (https://www.nuget.org/downloads) to ensure that what PS or `dotnet nuget` is resolving can be ignored (as you can see in the dumps above, there is no version information in the output).

Now I at least get the latest version. But `nuget push --help` is still not working:

```
PS D:\projects> nuget update --help
Unknown option: '--help'
NuGet.Commands.CommandException: Unknown option: '--help'
   at NuGet.CommandLine.CommandLineParser.GetPartialOptionMatch[TVal](IEnumerable`1 source, Func`2 getDisplayName, Func`2 getAltName, String option, String value)
   at NuGet.CommandLine.CommandLineParser.ExtractOptions(ICommand command, IEnumerator`1 argsEnumerator)
   at NuGet.CommandLine.CommandLineParser.ParseCommandLine(IEnumerable`1 commandLineArgs)
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```

**Comment by abelbraaksma** [comment]
Interesting.. It is now `-help`, not `--help` anymore:

But this fails:

```
PS D:\projects> nuget -help
Unknown command: '-help'
NuGet.Commands.CommandException: Unknown command: '-help'
   at NuGet.CommandLine.CommandManager.GetCommand(String commandName)
   at NuGet.CommandLine.CommandLineParser.ParseCommandLine(IEnumerable`1 commandLineArgs)
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```

This succeeds:
```
PS D:\projects> nuget update -help
usage: NuGet update <packages.config|solution|project>

Update packages to latest available versions. This command also updates NuGet.exe itself.

options:

-Source                 +      A list of package sources to search for updates.
-Id                     +      Package ids to update.
```

So, TLDR, you just need to know the commands that you want to ask help for. Perhaps a suggestion would be to print a minimal help output for "unknown command" errors?

**Comment by abelbraaksma** [comment]
I think the confusing part comes from me using `dotnet nuget` which works quite differently from just `nuget` commands.
