### ISSUE TITLE
dotnet watch test doesn't run tests in dotnet 8

### ISSUE THREAD

**Issue by yori-s** [dotnet/sdk#34949]
### Describe the bug
**dotnet test** works fine but **dotnet watch test** doesn't execute any tests.

### To Reproduce
Create a failing test (using docker below)
```
docker run --rm -it --name dotnet8-watch mcr.microsoft.com/dotnet/sdk:8.0.100-preview.7-jammy bash

mkdir /app && cd $_
dotnet new xunit
cat > UnitTest1.cs <<- EOF
namespace app;

public class UnitTest1
{
  [Fact] public void Fail() => Assert.True(false);
}
EOF
```

`dotnet watch test` just sits with something like the following:
```
dotnet watch : Polling file watcher is enabled
dotnet watch : Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload.
   Press "Ctrl + R" to restart.
dotnet watch : Building...
  Determining projects to restore...
  All projects are up-to-date for restore.
/usr/share/dotnet/sdk/8.0.100-preview.7.23376.3/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(314,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/app/app.csproj]
  app -> /app/bin/Debug/net8.0/app.dll
dotnet watch : Started
dotnet watch : Exited
dotnet watch : Waiting for a file to change before restarting dotnet...
```

Works fine in dotnet 7 (`mcr.microsoft.com/dotnet/sdk:7.0-jammy`)

### Further technical details
- Include the output of `dotnet --info`
   ```
   .NET SDK:
    Version:   8.0.100-preview.7.23376.3
    Commit:    daebeea8ea
 
   Runtime Environment:
    OS Name:     ubuntu
    OS Version:  22.04
    OS Platform: Linux
    RID:         ubuntu.22.04-x64
    Base Path:   /usr/share/dotnet/sdk/8.0.100-preview.7.23376.3/
 
   .NET workloads installed:
   There are no installed workloads to display.
 
   Host:
     Version:      8.0.0-preview.7.23375.6
     Architecture: x64
     Commit:       65b696cf5e
     RID:          linux-x64
 
   .NET SDKs installed:
     8.0.100-preview.7.23376.3 [/usr/share/dotnet/sdk]
 
   .NET runtimes installed:
     Microsoft.AspNetCore.App 8.0.0-preview.7.23375.9 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
     Microsoft.NETCore.App 8.0.0-preview.7.23375.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
 
   Other architectures found:
     None
 
   Environment variables:
     Not set
 
   global.json file:
     Not found
   ```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by yori-s** [comment]
Seems to be calling `dotnet exec` rather than `dotnet test`?

8.0 verbose output snippet:
```
dotnet watch : Running dotnet with the following arguments: 'test --no-restore'
dotnet watch : Started 'dotnet' 'exec "/app/bin/Debug/net8.0/app.dll"' with process id 202
dotnet watch : Started
dotnet watch : Process id 202 ran for 135ms
dotnet watch : Exited
dotnet watch : Waiting for a file to change before restarting dotnet...
```

7.0:
```
dotnet watch : Started '/usr/share/dotnet/dotnet' 'test --no-restore' with process id 138
dotnet watch : Running dotnet with the following arguments: test --no-restore
dotnet watch : Started
...
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
...
dotnet watch : Process id 138 ran for 6205ms
dotnet watch : Exited with error code 1
dotnet watch : Waiting for a file to change before restarting dotnet...
```

**Comment by yori-s** [comment]
Appears to have regressed after 8.0-preview2, which skipped hot reload in the `dotnet watch test` case.

* `CommandLineOptions` results in a no-op `dotnet run test` when hot reload is off:
  https://github.com/dotnet/sdk/blob/0a6f8335c92725de0e65df952f6940d3f7fadaf1/src/BuiltInTools/dotnet-watch/CommandLineOptions.cs#L236-L242

* `HotReloadDotNetWatcher` uses `RunArguments` from `MsBuildFileSetFactory`, spawning something like `dotnet exec some.dll`:
  https://github.com/dotnet/sdk/blob/0a6f8335c92725de0e65df952f6940d3f7fadaf1/src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs#L295-L304

**Comment by Odonno** [comment]
Seems like I have the same problem. Any solution?

**Comment by thomazmoura** [comment]
I've just checked and this is happening on the release version too. I tried both on Windows and on WSL2 (both running the 8.0.100 SDK) and on neither the tests are run. This really breaks my workflow since I use `dotnet watch test` extensively.

**Comment by leidegre** [comment]
I would like to know how this was released into the wild without anyone responsible for QA ran the the `dotnet watch test` command?

As a workaround you can put this `global.json` in your workspace to "downgrade" until this issue is resolved. Assuming you have a net7.0 SDK installation. You can list them via the `dotnet --list-sdks` command.

```json
{
  "sdk": {
    "version": "7.0.404"
  }
}
```

`dotnet watch test` is like to most useful command ever, please make it a priority of fix this. It is incredibly annoying to have to troubleshoot your workflow when all you want to do is to move on and make progress.

**Comment by baronfel** [comment]
cc @tmat can you please take a look at this? There are a few watch-related issues logged against the GA.

**Comment by onionhammer** [comment]
Defini

> This really breaks my workflow since I use `dotnet watch test` extensively.

Ditto

**Comment by dahovey** [comment]
Can someone please advise on the status of a fix?

It is disappointing that this core dotnet CLI command is broken...and how long it has been open, despite the holidays.

**Comment by baronfel** [comment]
This should be released in this month's servicing fix for .NET 8, which should drop this week. This bug is a bad one, and it sucks that we didn't catch it in time for the release - we're very sorry for the delay all around.

**Comment by dahovey** [comment]
Thanks for the quick response.

**Comment by thomazmoura** [comment]
> This should be released in this month's servicing fix for .NET 8, which should drop this week. This bug is a bad one, and it sucks that we didn't catch it in time for the release - we're very sorry for the delay all around.

I'm confused. You mention this should be fixed on this moth's servicing fix .NET 8 that would drop this week. Do you mean version 8.0.101?

Because on the download page it mentions it was released 9 of january (today or yesterday depending on time zone) but I've tested it both on Windows and Linux (WSL2 running Ubuntu22.04) and on both it seems to have the same behavior as before - it says it's running with hot reload on but runs no test at all. Disabling hot reload does not help either. I've tested with a previous .NET 6 project (running with the 8.0.101) and on a just created new project with the xunit template.

**Comment by cr3wdayt5p** [comment]
I can confirm that `dotnet watch` is still broken in SDK `8.0.101`.

Also `dotnet-core-uninstall` (https://github.com/dotnet/cli-lab/releases) have not yet been updated to support uninstall of `8.*.*` versions. So it is difficult to know if the broken stuff from `8.0.100` is affecting us.

**Comment by baronfel** [comment]
@tmat can you help verify which version should have received the fix?

**Comment by tmat** [comment]
Confirmed that the fix is in 8.0.200-preview.23628.6.

**Comment by baronfel** [comment]
@cr3wdayt5p / @thomazmoura / @dahovey et al - I'm very sorry, I was going from memory and not the actual data. This fix will first be available in the February Servicing fix for the .NET SDK/Runtime. The linked PR (https://github.com/dotnet/sdk/pull/37233) is tagged with the 8.0.2 milestone, which is our release process' way of saying 'the second servicing release'.

So next month, in 8.0.102 and 8.0.200 this fix will be released to the general public in a stable form.

**Comment by TomasEkeli** [comment]
i know this isn't constructive comment, but i find it troubling that dotnet watch  is allowed to be broken for months. i thought leaving it to january was bad.

**Comment by MarkusRodler** [comment]
I tried it with 8.0.200 on WSL (Debian) and it does not work with this way:
`dotnet watch --project Test "msbuild" /t:testmsbuild`

Snippet from Test.csproj:
```csproj
    <Target Name="testmsbuild">
        <Exec Command="dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:ExcludeByFile=\&quot;**/Program.cs,**/ExceptionHandler.cs,**/*.razor,**/*.g.cs\&quot;" />
        <Exec Command="dotnet reportgenerator &quot;-reports:coverage.cobertura.xml&quot; &quot;-targetdir:../Client/wwwroot/Coverage&quot; -reporttypes:HTML;" />
        <Delete Files="coverage.cobertura.xml" />
        <RemoveDir Directories="TestResults" Condition="Exists('TestResults')" />
    </Target>
```

Output:
![Screenshot 2024-02-14 144350](https://github.com/dotnet/sdk/assets/14873906/6a42c904-d6a3-4e6e-b4ba-f4ed15a5bde9)

**Comment by arampp** [comment]
Hint when working with dev-containers:
The latest [dotnet dev-cotainer](https://mcr.microsoft.com/en-us/product/devcontainers/dotnet/) is still shipped with the broken dotnet 8.0.101.

But you can add the latest release as a feature. Add this snippet to your `devcotainer.json`:

```json
    "features": {
        "ghcr.io/devcontainers/features/dotnet:2": {
            "version": "8.0"
        }
    }
```
After a rebuild, the latest and fixed dotnet cli will be available.

**Comment by laurentpayot** [comment]
Now working on my [Elmish example repo](https://github.com/laurentpayot/fsharp-fable-elmish-example). Thanks!
