### ISSUE TITLE
Publishing Native AOT in Release mode still producing .pdb files

### ISSUE THREAD

**Issue by ScottKane** [dotnet/sdk#34959]
![image](https://github.com/dotnet/sdk/assets/17254944/238d91d6-a621-4e15-acdb-0733ba119134)

`dotnet publish -c Release`

![image](https://github.com/dotnet/sdk/assets/17254944/6476ded2-244a-465f-9339-60b20e569ae9)

Why is this happening when I have explicitly turned this behaviour off?

.NET version: `8.0.100-preview.7.23376.3`

**Comment by baronfel** [comment]
Sorry @ScottKane - we use a bot to categorize incoming issues since many teams control different areas of the SDK repo. The bot classified this incorrectly as NuGet, and the NuGet team prefers to have all of their issues on their single repo.

I've recategorized this issue and reopened it, the appropriate team will triage as they have availability.

**Comment by ScottKane** [comment]
Great thanks!

**Comment by vitek-karas** [comment]
I think https://github.com/dotnet/runtime/pull/89840 should fix this - I guess it should be part of RC1.
@MichalStrehovsky

**Comment by MichalStrehovsky** [comment]
> I think [dotnet/runtime#89840](https://github.com/dotnet/runtime/pull/89840) should fix this - I guess it should be part of RC1. @MichalStrehovsky

The quoted PR only fixed this on Linux that started to have different behavior due to StripSymbols.

On Windows, this already works, probably since .NET 7. @ScottKane you just need to delete your output before you run publish. Notice that on your screenshot, the PDB has a timestamp of 16:24, while the exe is timestamped at 16:33. The PDB is from an old build that did generate a PDB. The latest build didn't generate one.

I'll close this as fixed.

**Comment by ali50m** [comment]
@baronfel @MichalStrehovsky @vitek-karas  Hi folks, I still see this issue with the latest .net 10 RC1.

After setting the properties in csproj and publish AOT still produce the big pdb file.
```xml
    <DebugSymbols>False</DebugSymbols>
    <DebugType>None</DebugType>
```

Env:
Windows 10 21H2 Iot LTSC 19044.6332
dotnet SDK 10.0.0-rc.1.25451.107

**Comment by Rast1234** [comment]
I believe there is a bug somewhere that doesn't close .pdb files until very end of whole build. With msbuild `delete` task and with `exec rm` task i can verify they do remove all pdbs, but after build ends there's still one pdb for .exe in the output.

Example project:
```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup>
        <PublishAot>true</PublishAot>
    </PropertyGroup>

    <Target Name="removePdb" AfterTargets="Publish">
        <Exec Command="echo ===before===" />
        <Exec Command="dir /b $(PublishDir)" /><!--pdb exists-->
        <Exec Command="del $(PublishDir)\*.pdb" /><!--pdb gets removed-->
        <Exec Command="echo ===after===" />
        <Exec Command="dir /b $(PublishDir)" /><!--pdb does not exist-->

        <!--yet it's still in output folder after publish is finished!-->
    </Target>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Lib\Lib.csproj" />
    </ItemGroup>

</Project>
```
Actual code and references are not important. And here's commandline:

```cmd
c:\vault\SharpGoo>dotnet publish src\Console -r win-x64 -o _publish -v:d && dir /b _publish
Restore complete (0.6s)
    Determining projects to restore...
    All projects are up-to-date for restore.
  DynamicDependenciesGenerator netstandard2.0 succeeded (0.1s) → src\DynamicDependenciesGenerator\bin\Release\netstandard2.0\DynamicDependenciesGenerator.dll
  Lib net10.0 succeeded (0.1s) → src\Lib\bin\Release\net10.0\Lib.dll
  Console net10.0 win-x64 succeeded (11.4s) → _publish\
    Generating native code
    ===before===
    Console.exe
    Console.pdb
    Lib.pdb
    ===after===
    Console.exe⬅️no PDBs in folder

Build succeeded in 12.7s
Console.exe
Console.pdb ⬅️ gets back from hell somehow. not Lib.pdb though!
```

It does not matter if ` -p:DebugType=None -p:DebugSymbols=false` present - they do work, but `Console.pdb` still gets created. If #16975 were a thing, you would've spotted this as regression :)

env: Windows 10.0.19045.6093, SDK 10.0.100

**Comment by MichalStrehovsky** [comment]
This really doesn't repro to me. If I make a `dotnet new console --aot` app and set `<DebugType>None</DebugType>`, I don't get the big PDB file (since DebugType on the entrypoint assembly dictates behavior for the entire AOT compilation).

I don't fully understand what the https://github.com/dotnet/sdk/issues/16975 linked issue is about. If this is about symbols getting copied to the output directory, there's `<CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>` property that controls that behavior (both for AOT and non-AOT).

I think both can be achieved: "I don't want PDB at all" and "I don't want PDB in the publish outputs".

**Comment by Rast1234** [comment]
> CopyOutputSymbolsToPublishDirectory

Thank you, this is what i was looking for! And i guess people in the linked issue too, at least regarding PDBs.

You see, when you want to publish a single .exe and get rid of .pdbs in publish output, naturally you start googling how to disable debug symbols generation and find `DebugType=none` + `DebugSymbols=false` options, which look like the right thing. But they are not. Here's repro: https://github.com/Rast1234/pdb_repro

So i guess it would help if `CopyOutputSymbolsToPublishDirectory` was more visible/documented...

**Comment by ali50m** [comment]
@MichalStrehovsky I make a non-AOT console project with a singlie library. After setting CopyOutputSymbolsToPublishDirectory to false on both projects and publish the console app. I cannot find the console pdb file, but the library pdb file still there.

Here is the reproduce [repo](https://github.com/ali50m/PublishTest).

<img width="1528" height="516" alt="Image" src="https://github.com/user-attachments/assets/96c2f9ca-20a9-4251-b954-53e478d823f0" />
