### ISSUE TITLE
[NETSDKE2E][ARM64] Install .net9preview3 X64 SDK create project on Arm64 OS, the system will be blocking.

### ISSUE THREAD

**Issue by v-ainigao** [dotnet/sdk#39513]
Repro steps:
1. Install .net9preview3 X64 SDK from https://aka.ms/dotnet/9.0.1xx/daily/dotnet-sdk-win-x64.exe
2. Modify the environment variable path to x64 "C:\Program Files\dotnet\x64".
3. Create new console app.
`dotnet new console `

Expected Result:
Project can be created successfully.

Actual Result:
Creating project or build fails and will be blocking.
![image](https://github.com/dotnet/sdk/assets/106054229/450652a9-1f69-4573-8320-dfc8656c58af)
![image](https://github.com/dotnet/sdk/assets/106054229/be099a99-0475-4891-a0cb-f817b8fc3c7b)

dotnet --info
.NET SDK:
 Version:           9.0.100-preview.3.24163.23
 Commit:            33549194e2
 Workload version:  9.0.100-manifests.42eb89a3
 MSBuild version:   17.10.0-preview-24162-02+0326fd7c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\x64\sdk\9.0.100-preview.3.24163.23\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      9.0.0-preview.3.24162.24
  Architecture: x64
  Commit:       e4fceb3ae5

.NET SDKs installed:
  9.0.100-preview.3.24163.23 [C:\Program Files\dotnet\x64\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-preview.3.24162.20 [C:\Program Files\dotnet\x64\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-preview.3.24162.24 [C:\Program Files\dotnet\x64\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 9.0.0-preview.3.24162.12 [C:\Program Files\dotnet\x64\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  arm64 [C:\Program Files\dotnet]
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by v-ainigao** [comment]
Install .net9preview3 X64 SDK create project on Arm64 OS is able to work normally.
![image](https://github.com/dotnet/sdk/assets/106054229/40cf6248-7091-4484-bfc1-4c37f61a53e9)

**Comment by richaverma1** [comment]
@v-ainigao is this a regression from .NET9 Preview 2?

**Comment by marcpopMSFT** [comment]
@elinor-fung @agocke since this appears to be a host crash

**Comment by elinor-fung** [comment]
@v-ainigao do you have a dump you could share?

Do other operations - for example `dotnet new list`, `dotnet build`, `dotnet tool install` - work? Does running an app that has already been built work (`dotnet <appDll>`)?

Since `dotnet --info` seems to work, this should not be a problem with the host itself.

**Comment by v-ainigao** [comment]
> @v-ainigao is this a regression from .NET9 Preview 2?

This issue does not repro with previous versions of net9preview3 and .net9preview2.

**Comment by v-ainigao** [comment]
> @v-ainigao do you have a dump you could share?
> 
> Do other operations - for example `dotnet new list`, `dotnet build`, `dotnet tool install` - work? Does running an app that has already been built work (`dotnet <appDll>`)?
> 
> Since `dotnet --info` seems to work, this should not be a problem with the host itself.

`dotnet new console`/`dotnet new list`/`dotnet build`/`dotnet tool install` is not working.
![image](https://github.com/dotnet/sdk/assets/106054229/c0b95adb-974a-47f3-86a4-30c17ee22988)
![image](https://github.com/dotnet/sdk/assets/106054229/49bf04fb-48a5-48ad-8c5a-c1764562ee73)
Running already built application not working.
![image](https://github.com/dotnet/sdk/assets/106054229/3b405e13-b212-41e6-bece-991befff9a5b)
But `dotnet --info` works fine.
![image](https://github.com/dotnet/sdk/assets/106054229/c2a9b64f-f803-4ee2-8384-3258409bf064)

**Comment by elinor-fung** [comment]
> Running already built application not working.

The screenshot shows `dotnet build`. Did you also check just running the application using `dotnet`? For example `dotnet bin\Release\net9.0\a.dll`.

> This memory dump file has been placed in this path. \mlangfs1\public\v-aini#39513dump file.zip

The main thread is waiting to suspend the runtime for a GC:
```
00  ARM64EC 0000000d`ca17cf80 00007ffe`14419094     ntdll!#ZwWaitForSingleObject+0x14
01  ARM64EC 0000000d`ca17cf90 00007ffe`1454d4b4     KERNELBASE!WaitForSingleObjectEx+0x84 [minkernel\kernelbase\synch.c @ 1328] 
02  ARM64EC 0000000d`ca17d020 00007ffd`a21ee540     KERNELBASE!$ientry_thunk$cdecl$i8$i8m8i8i8+0x24
03    AMD64 (Inline Function) --------`--------     coreclr!CLREventWaitHelper2+0x6 [D:\a\_work\1\s\src\coreclr\vm\synch.cpp @ 372] 
04    AMD64 0000000d`ca17d0d0 00007ffd`a221a13e     coreclr!CLREventWaitHelper+0x20 [D:\a\_work\1\s\src\coreclr\vm\synch.cpp @ 397] 
05    AMD64 (Inline Function) --------`--------     coreclr!CLREventBase::WaitEx+0xf [D:\a\_work\1\s\src\coreclr\vm\synch.cpp @ 466] 
06    AMD64 (Inline Function) --------`--------     coreclr!CLREventBase::Wait+0xf [D:\a\_work\1\s\src\coreclr\vm\synch.cpp @ 412] 
07    AMD64 0000000d`ca17d130 00007ffd`a2238912     coreclr!ThreadSuspend::SuspendRuntime+0x31e [D:\a\_work\1\s\src\coreclr\vm\threadsuspend.cpp @ 3600] 
08    AMD64 0000000d`ca17d230 00007ffd`a223862a     coreclr!ThreadSuspend::SuspendEE+0x116 [D:\a\_work\1\s\src\coreclr\vm\threadsuspend.cpp @ 5778] 
09    AMD64 0000000d`ca17d310 00007ffd`a2238177     coreclr!GCToEEInterface::SuspendEE+0x26 [D:\a\_work\1\s\src\coreclr\vm\gcenv.ee.cpp @ 51] 
0a    AMD64 0000000d`ca17d340 00007ffd`a22384be     coreclr!WKS::GCHeap::GarbageCollectGeneration+0xf3 [D:\a\_work\1\s\src\coreclr\gc\gc.cpp @ 50661] 
0b    AMD64 0000000d`ca17d390 00007ffd`a22fac8a     coreclr!WKS::gc_heap::trigger_gc_for_alloc+0x26 [D:\a\_work\1\s\src\coreclr\gc\gc.cpp @ 18788] 
0c    AMD64 0000000d`ca17d3c0 00007ffd`a22a99f5     coreclr!WKS::gc_heap::try_allocate_more_space+0x5126e [D:\a\_work\1\s\src\coreclr\gc\gc.cpp @ 18915] 
0d    AMD64 0000000d`ca17d420 00007ffd`a21de818     coreclr!WKS::gc_heap::allocate_more_space+0x31 [D:\a\_work\1\s\src\coreclr\gc\gc.cpp @ 19415] 
0e    AMD64 (Inline Function) --------`--------     coreclr!WKS::gc_heap::allocate+0x5a [D:\a\_work\1\s\src\coreclr\gc\gc.cpp @ 19446] 
0f    AMD64 0000000d`ca17d450 00007ffd`a21c730d     coreclr!WKS::GCHeap::Alloc+0x88 [D:\a\_work\1\s\src\coreclr\gc\gc.cpp @ 49629] 
10    AMD64 (Inline Function) --------`--------     coreclr!Alloc+0xb6 [D:\a\_work\1\s\src\coreclr\vm\gchelpers.cpp @ 227] 
11    AMD64 (Inline Function) --------`--------     coreclr!AllocateObject+0x128 [D:\a\_work\1\s\src\coreclr\vm\gchelpers.cpp @ 1095] 
12    AMD64 (Inline Function) --------`--------     coreclr!AllocateObject+0x12e [D:\a\_work\1\s\src\coreclr\vm\gchelpers.h @ 68] 
13    AMD64 0000000d`ca17d490 00007ffd`a031ef0b     coreclr!JIT_New+0x20d [D:\a\_work\1\s\src\coreclr\vm\jithelpers.cpp @ 2481] 
```

@dotnet/dotnet-diag I can't seem to get sos working for the dump. This is x64 dotnet running on arm64 Windows. The identified target architecture 0xa641 isn't listed as an IMAGE_FILE_MACHINE value - any ideas?
```
SOS does not support the current target architecture '' (0xa641). A 32 bit target may require a 32 bit debugger or vice versa. In general, try to use the same bitness for the debugger and target process.
```

**Comment by mikem8361** [comment]
You must be running on a arm64ec (0xa641).  There is already a diagnostic repo [issue](https://github.com/dotnet/diagnostics/issues/4430) and a [PR](https://github.com/dotnet/diagnostics/pull/2858) that Juan started but still needs some finishing touches to fix this.

**Comment by v-jieyan2** [comment]
This problem has been fixed.
![image](https://github.com/dotnet/sdk/assets/106043919/4f85a965-c6b7-456c-8ab7-839b36bf8245)
![image](https://github.com/dotnet/sdk/assets/106043919/b9a5f3d0-8d32-4224-9313-716183387a9b)
![image](https://github.com/dotnet/sdk/assets/106043919/035b97b0-e0c5-42d7-ae70-270fa7fc6a1c)

**Comment by v-ainigao** [comment]
This issue still occurs today on ARM64 win11.
This memory dump file has been placed in this path. \\mlangfs1\public\v-aini\#39513dump file(2)\dumpfile.zip
CLI version: .net9.0.100-preview.3.24165.20(runtime-9.0.0-preview.3.24162.31)
![image](https://github.com/dotnet/sdk/assets/106054229/ce69f3ce-b438-4fa3-944e-700dbcba854c)

**Comment by v-ainigao** [comment]
This issue still repro's on .net9.0.100-preview.3.24175.24(runtime-9.0.0-preview.3.24172.9) x64 SDK on ARM64OS.
![image](https://github.com/dotnet/sdk/assets/106054229/9fe2f774-d84e-4b57-a869-959eb3a67dd5)
![image](https://github.com/dotnet/sdk/assets/106054229/d3f5a957-4325-4fca-9d73-426e44487a33)

**Comment by richaverma1** [comment]
@marcpopMSFT is this blocking .NET 9 Preview 3 release? It is a regression from Preview 2.

**Comment by marcpopMSFT** [comment]
@richaverma1 do other scenarios work (ie build, running an app with dotnet, etc)?

since it's the host crashing and Elinor appears blocked analyzing the dump because of an unrelated issue, not sure how to tell how critical this is without knowing what additional scenarios might be impacted.

CC @baronfel @elinor-fung

**Comment by marcpopMSFT** [comment]
If it's limited to workload installs when running the x64 sdk on an arm64 machine, I wouldn't make it a blocker.

**Comment by richaverma1** [comment]
@marcpopMSFT it is failing on the basic scenario of creating a console app. But on ARM64 OS with x64 SDK. Not sure how many customers use that config.
