### ISSUE TITLE
Workload install error - Unable to install maui workload on Windows - .NET 9 Preview 3

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/sdk#40221]
### Description

Workload install error - Unable to install maui workload on Windows - .NET 9 Preview 3

Workload installation failed: One or more errors occurred. (Version 17.0.8519 of package microsoft.ios.sdk.net8.0_17.0.msi.x64 is not found in NuGet feeds https://api.nuget.org/v3/index.json;C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\)

### Steps to Reproduce

```shell
dotnet workload install maui
```

### Link to public reproduction project repository

Workload install issue

### Version with bug

9.0.0-preview.3.10457

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

9.0.0-preview.2.10293

### Affected platforms

iOS

### Affected platform versions

iOS

### Did you find any workaround?

None

### Relevant log output

```shell
Workload installation failed: One or more errors occurred. (Version 17.0.8519 of package microsoft.ios.sdk.net8.0_17.0.msi.x64 is not found in NuGet feeds https://api.nuget.org/v3/index.json;C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\)
```

**Comment by caliberdigitalllc** [comment]
adding the sources to Windows: %appdata%\NuGet\NuGet.Config from https://github.com/dotnet/maui/blob/net9.0/NuGet.config fixed it for me.

**Comment by rolfbjarne** [comment]
> > (When something like this happen, I tend to try copying sources from [dotnet/maui@`net9.0`/NuGet.config](https://github.com/dotnet/maui/blob/net9.0/NuGet.config?rgh-link-date=2024-04-15T08%3A30%3A26Z). Maybe it would help here. IDK.)
> 
> This does not work either. I tried using `https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json` in the -s parameter.

I believe this is the feed you need:

> https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json

**Comment by rolfbjarne** [comment]
I believe I've fixed this now, packages have been pushed.

**Comment by TommiGustafsson-HMP** [comment]
It's still not working perfectly. If we try to do Pair to Mac, there's this error:

![image](https://github.com/dotnet/sdk/assets/16661034/d45b8652-394b-4fe7-acf8-1c8b49bc4191)

However, if we add NuGet.config to our .NET 9.0 MAUI project like this:

https://github.com/dotnet/maui/blob/net9.0/NuGet.config

The error goes away.

**Comment by rolfbjarne** [comment]
> It's still not working perfectly. If we try to do Pair to Mac, there's this error:
> 
> ![image](https://private-user-images.githubusercontent.com/16661034/323952032-d45b8652-394b-4fe7-acf8-1c8b49bc4191.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MzMxNTMsIm5iZiI6MTcxMzUzMjg1MywicGF0aCI6Ii8xNjY2MTAzNC8zMjM5NTIwMzItZDQ1Yjg2NTItMzk0Yi00ZmU3LWFjZjgtMWM4YjQ5YmM0MTkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDEzMjA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNGVmZDI2ZjJlMzg5MGFmNGZhZDk3YTI3MzdhODlmZmZiMDhmZWZlMTdjZWQxMTUwYzUyOTgzYmI2MDBjMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yNLwN1RVpFOVObwGOuyTnUhJRCCoTnL2MyoRNcKNHZ8)
> 
> However, if we add NuGet.config to our .NET 9.0 MAUI project like this:
> 
> [dotnet/maui@`net9.0`/NuGet.config](https://github.com/dotnet/maui/blob/net9.0/NuGet.config?rgh-link-date=2024-04-19T12%3A17%3A59Z)
> 
> The error goes away.

I think you somehow picked up some preview 4 builds from those additional feeds at some point, because preview 4 packages are not supposed to be on nuget.org yet.

**Comment by TommiGustafsson-HMP** [comment]
We are not sure why it is looking for preview4 packages. We have defined preview3 SDK in our global.json.

**Comment by janne-hmp** [comment]
I can confirm that the iOS workload download (on Mac especially when Pairing to Mac from Windows) is still not working as of now.

**Comment by rolfbjarne** [comment]
If you still have problems, please try to completely remove .NET, make sure you don't have any custom NuGet sources, and then try to install .NET 9 preview 3 again.

**Comment by janne-hmp** [comment]
This is a problem on the Mac side when pairing to Mac. What is the best way of removing .NET from Mac? Pair to Mac functionality on Windows has been handling everything so far for me.

**Comment by rolfbjarne** [comment]
> This is a problem on the Mac side when pairing to Mac. What is the best way of removing .NET from Mac? Pair to Mac functionality on Windows has been handling everything so far for me.

The pairing to Mac functionality installs whatever is installed on the Windows machine; which means that starting from a clean slate on Windows is likely to fix the problem on the Mac too.

In the case this isn't so, pair to Mac installs .NET here:

> ~/Library/Caches/Xamarin/XMA/SDKs/dotnet

You can remove this directory (or rename it, so you can add it back if something goes wrong)

**Comment by janne-hmp** [comment]
Thanks, we'll check this out.
