### ISSUE TITLE
Publishing native AOT fails on Fedora 40, Documentation suggests packages only for Ubuntu

### ISSUE THREAD

**Issue by photex** [dotnet/sdk#42335]
### Describe the bug
I've seen #37995 and the solution doesn't generally apply to Fedora 40. The dotnet documentation is unfortunately Ubuntu specific and would not apply to RHEL distros or Fedora.

Instead you need to install `zlib-ng-devel`, and `zlib-ng-compat-devel`.

### To Reproduce
```
chipc@fedora:~/workspaces/slowgames$ mkdir testproj
chipc@fedora:~/workspaces/slowgames$ cd testproj
chipc@fedora:~/workspaces/slowgames/testproj$ dotnet new console
The template "Console App" was created successfully.

Processing post-creation actions...
Restoring /home/chipc/workspaces/slowgames/testproj/testproj.csproj:
  Determining projects to restore...
  Restored /home/chipc/workspaces/slowgames/testproj/testproj.csproj (in 224 ms).
Restore succeeded.
chipc@fedora:~/workspaces/slowgames/testproj$ dotnet publish -c Release -r linux-x64 -p:PublishAOT=true
MSBuild version 17.8.5+b5265ef37 for .NET
  Determining projects to restore...
  Restored /home/chipc/workspaces/slowgames/testproj/testproj.csproj (in 406 ms).
  testproj -> /home/chipc/workspaces/slowgames/testproj/bin/Release/net8.0/linux-x64/testproj.dll
  Generating native code
  /usr/bin/ld.bfd: cannot find -lz: No such file or directory
collect2 : error : ld returned 1 exit status [/home/chipc/workspaces/slowgames/testproj/testproj.csproj]
/home/chipc/.nuget/packages/microsoft.dotnet.ilcompiler/8.0.5/build/Microsoft.NETCore.Native.targets(366,5): error MSB3073: The command ""gcc" "obj/Release/net8.0/linux-x64/native/testproj.o" -o "bin/Release/net8.0/linux-x64/native/testproj" -Wl,--version-script=obj/Release/net8.0/linux-x64/native/testproj.exports -Wl,--export-dynamic -gz=zlib -fuse-ld=bfd /home/chipc/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.5/sdk/libbootstrapper.o /home/chipc/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.5/sdk/libRuntime.WorkstationGC.a /home/chipc/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.5/sdk/libeventpipe-disabled.a /home/chipc/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.5/sdk/libstdc++compat.a /home/chipc/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.5/framework/libSystem.Native.a /home/chipc/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.5/framework/libSystem.Globalization.Native.a /home/chipc/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.5/framework/libSystem.IO.Compression.Native.a /home/chipc/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.5/framework/libSystem.Net.Security.Native.a /home/chipc/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.5/framework/libSystem.Security.Cryptography.Native.OpenSsl.a -g -Wl,-rpath,'$ORIGIN' -Wl,--build-id=sha1 -Wl,--as-needed -pthread -ldl -lz -lrt -lm -pie -Wl,-pie -Wl,-z,relro -Wl,-z,now -Wl,--eh-frame-hdr -Wl,--discard-all -Wl,--gc-sections" exited with code 1. [/home/chipc/workspaces/slowgames/testproj/testproj.csproj]
chipc@fedora:~/workspaces/slowgames/testproj$ sudo dnf install zlib-ng-compat-devel
Last metadata expiration check: 0:54:44 ago on Wed 24 Jul 2024 09:44:06 AM CEST.
Dependencies resolved.
========================================================================================================================================
 Package                                  Architecture               Version                          Repository                   Size
========================================================================================================================================
Installing:
 zlib-ng-compat-devel                     x86_64                     2.1.7-1.fc40                     updates                      38 k

Transaction Summary
========================================================================================================================================
Install  1 Package

Total download size: 38 k
Installed size: 107 k
Is this ok [y/N]: y
Downloading Packages:
zlib-ng-compat-devel-2.1.7-1.fc40.x86_64.rpm                                                            489 kB/s |  38 kB     00:00
----------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                    62 kB/s |  38 kB     00:00
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                1/1
  Installing       : zlib-ng-compat-devel-2.1.7-1.fc40.x86_64                                                                       1/1
  Running scriptlet: zlib-ng-compat-devel-2.1.7-1.fc40.x86_64                                                                       1/1

Installed:
  zlib-ng-compat-devel-2.1.7-1.fc40.x86_64

Complete!
chipc@fedora:~/workspaces/slowgames/testproj$ dotnet publish -c Release -r linux-x64 -p:PublishAOT=true
MSBuild version 17.8.5+b5265ef37 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  testproj -> /home/chipc/workspaces/slowgames/testproj/bin/Release/net8.0/linux-x64/testproj.dll
  testproj -> /home/chipc/workspaces/slowgames/testproj/bin/Release/net8.0/linux-x64/publish/
```

### Further technical details
```
.NET SDK:
 Version:           8.0.105
 Commit:            eae90abaaf
 Workload version:  8.0.302-baseline.24280.2

Runtime Environment:
 OS Name:     fedora
 OS Version:  40
 OS Platform: Linux
 RID:         fedora.40-x64
 Base Path:   /usr/lib64/dotnet/sdk/8.0.105/

.NET workloads installed:
 Workload version: 8.0.302-baseline.24280.2
There are no installed workloads to display.

Host:
  Version:      8.0.5
  Architecture: x64
  Commit:       087e15321b

.NET SDKs installed:
  8.0.105 [/usr/lib64/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.5 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.5 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/lib64/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by marcpopMSFT** [comment]
Triage: @agocke the docs for this are here: https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/?tabs=linux-rhel%2Cnet8#prerequisites Is this missing a few prereqs for fedora and should we just update the docs for this?

**Comment by agocke** [comment]
https://github.com/agocke/dotnet-docs/pull/1871

**Comment by cdock1029** [comment]
I'm getting restore error on Fedora trying to make simple AOT console project out of the box.

```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishAot>true</PublishAot>
    </PropertyGroup>

</Project>
```

`error NU1101: Unable to find package runtime.fedora.43-x64.Microsoft.DotNet.ILCompiler.`

`Failed to restore`

For some reason, Fedora sets their RID in a non standard way: `RID: fedora.43-x64` instead of `linux-x64` so the package uri is defined wrong.

`dotnet --info`

```
dotnet --info
.NET SDK:
 Version:           10.0.100
 Commit:            b0f34d51fc
 Workload version:  10.0.100-manifests.4eab3e0f
 MSBuild version:   18.0.2+b0f34d51f

Runtime Environment:
 OS Name:     fedora
 OS Version:  43
 OS Platform: Linux
 RID:         fedora.43-x64
 Base Path:   /usr/lib64/dotnet/sdk/10.0.100/

.NET workloads installed:
There are no installed workloads to display.
Configured to use workload sets when installing new manifests.
No workload sets are installed. Run "dotnet workload restore" to install a workload set.

Host:
  Version:      10.0.0
  Architecture: x64
  Commit:       b0f34d51fc

.NET SDKs installed:
  10.0.100 [/usr/lib64/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 10.0.0 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 10.0.0 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_BUNDLE_EXTRACT_BASE_DIR           [/home/cdock/.cache/dotnet_bundle_extract]
  DOTNET_ROOT                              [/usr/lib64/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

```

**Comment by cdock1029** [comment]
Ok disregard: I just need to override the runtime identifier and define it in my csproj:

`<RuntimeIdentifier>linux-x64</RuntimeIdentifier>`

**Comment by tmds** [comment]
> error NU1101: Unable to find package runtime.fedora.43-x64.Microsoft.DotNet.ILCompiler.

@cdock1029 I am trying to reproduce the error.

In a Fedora 43 container (`podman run -ti fedora:43`):

```
dnf install -y dotnet-sdk-10.0 clang
cd /tmp
dotnet new console --no-restore -o console
cd console
cat >console.csproj <<EOF
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishAot>true</PublishAot>
    </PropertyGroup>

</Project>
EOF
dotnet publish
```

The publish works:
```
Restore complete (9.8s)
  console net10.0 linux-x64 succeeded (3.4s) → bin/Release/net10.0/linux-x64/publish/

Build succeeded in 13.4s
```

.NET SDK in the container is 10.0.101.

Can you still reproduce the issue? Any thoughts on what I should change?

> It's very possible that Linux distributions will change packages around again, but we can continue to update.

@marcpopMSFT @agocke In https://learn.microsoft.com/en-us/dotnet/core/distribution-packaging we define a package `dotnet-sdk-aot-[major].[minor]` that is meant to install Native AOT dependencies. The package shifts the maintenance responsibility to the package maintainers. Fedora has this package.

**Comment by kw-pro** [comment]
> Can you still reproduce the issue? Any thoughts on what I should change?

I think the problem is fixed.
One week ago I can't build a .NET project on my local Fedora 43 but today I can.

**Comment by NWoodsman** [comment]
This shouldn't be closed. I'm still getting this error when attempting to run a single-file app. This should be reopened until fix is documented for single file apps. [`This issue`](https://github.com/dotnet/sdk/issues/52285) was also closed without a documented fix. The fix cannot include editing csproj files.

**Comment by yoshiask** [comment]
@NWoodsman I was just experiencing this issue on Fedora 43 with the .NET 10 SDK. Updating the SDK from 10.0.101 to 10.0.201 fixed the issue for me. Note that I had to use the `dotnet-install` script to set the install directory since it appears the RPM package is still on 10.0.101.

<img width="1907" height="873" alt="Image" src="https://github.com/user-attachments/assets/4599e8c3-7879-4f17-b6c9-d5098bdf9d5e" />

**Comment by agocke** [comment]
@NWoodsman  this issue is about native aot. Can you describe the issue you’re having with single file and how to reproduce it?

**Comment by tmds** [comment]
> Updating the SDK from 10.0.101 to 10.0.201 fixed the issue for me. Note that I had to use the dotnet-install script to set the install directory since it appears the RPM package is still on 10.0.101.

I have 10.0.103 installed from rpms. You should be able to upgrade to that. Fedora doesn't provide the additional bands like 10.0.2xx.

The fix should be in 10.0.104 which was released last week but does not seem to be on Fedora yet.

cc @omajid
