### ISSUE TITLE
SDK 8.0.401: `dotnet workload install wasm-tools ` does not install correctly

### ISSUE THREAD

**Issue by JCKortlang** [dotnet/sdk#42919]
### Describe the bug
`dotnet workload install wasm-tools ` supposedly succeeds but there is a warning indicating a failure. The tool is listed as install but attempting to compile a wasm project fails.

```
sudo dotnet workload install wasm-tools

Welcome to .NET 8.0!
---------------------
SDK Version: 8.0.401

Writing workload pack installation record for Microsoft.NET.Runtime.Emscripten.3.1.34.Sdk.osx-x64 version 8.0.8...
Warning: Workload garbage collection failed with error: Workload version 8.0.401-baseline.24412.2 was not found..
```

```
dotnet workload list

Installed Workload Id      Manifest Version      Installation Source
--------------------------------------------------------------------
wasm-tools                 8.0.8/8.0.100         SDK 8.0.400
```

```
sudo dotnet workload uninstall wasm-tools

Welcome to .NET 8.0!
---------------------
SDK Version: 8.0.401

Removing workload installation record for wasm-tools...
Workload uninstallation failed: Workload version 8.0.401-baseline.24412.2 was not found.
```

### To Reproduce

1. On OSX 13.6.9 (22G830) 
2. Download / Install .NET 8.0.401 SDK -- https://dotnet.microsoft.com/en-us/download/dotnet/8.0
3. Run, `sudo dotnet workload uninstall wasm-tools`
4. Attempt to compile a wasm project that depends on wasm-tools.

### Exceptions (if any)

```
Warning: Workload garbage collection failed with error: Workload version 8.0.401-baseline.24412.2 was not found
```

```
Workload uninstallation failed: Workload version 8.0.401-baseline.24412.2 was not found
```

### Further technical details
- SDK Version: 8.0.401
- OS: MacOS 13.6.9 (22G830)

### Mitigation
1. Rollback SDK version
2. Run `sudo dotnet workload clean`
3. Reinstall `wasm-tools`

**Comment by davishoang96** [comment]
Confirmed. Can't build blazor wasm project after install wasm-tools.

**Comment by Robbware** [comment]
Just ran into this issue too.

**Comment by borag** [comment]
I have the same

**Comment by rbev** [comment]
confirmed, but i don't think it's related to wasm-tools

* Uninstalled dotnet
* removed the `/usr/local/share/dotnet` folder for good measure
* install net 8.0.401
``` 
❯ brew install --cask dotnet-sdk8
==> Downloading https://github.com/isen-ng/homebrew-dotnet-sdk-versions/raw/master/META.md
Already downloaded: /Users/rhysbevilaqua/Library/Caches/Homebrew/downloads/676efe54d94c945edc1937e1e849eb5fc52f70879490e21ffc1cadeda530def6--META.md
Warning: No checksum defined for cask 'dotnet-sdk8', skipping verification.
==> Installing dependencies: dotnet-sdk8-0-400
==> Caveats
Uninstalling the offical dotnet-sdk casks will remove the shared runtime dependencies, so you'll need to reinstall the particular version cask you want from this tap again for the `dotnet` command to work again.

==> Downloading https://download.visualstudio.microsoft.com/download/pr/1764cd94-29ac-46b2-b308-77d02b47486d/8397cdc3d842a60f062f1a08199a4974/dotnet-sdk-8.0.401-osx-arm64.pkg
Already downloaded: /Users/rhysbevilaqua/Library/Caches/Homebrew/downloads/35166c11939a7f64ea8a5edc012c5684672ddfa3e45de43e00e828e9ff9a6920--dotnet-sdk-8.0.401-osx-arm64.pkg
==> Installing Cask dotnet-sdk8-0-400
==> Running installer for dotnet-sdk8-0-400 with sudo; the password may be necessary.
Password:
installer: Package name is Microsoft .NET SDK 8.0.401 (arm64)
installer: Upgrading at base path /
installer: The upgrade was successful.
🍺  dotnet-sdk8-0-400 was successfully installed!
==> Installing Cask dotnet-sdk8
🍺  dotnet-sdk8 was successfully installed!
==> Caveats
==> dotnet-sdk8-0-400
Uninstalling the offical dotnet-sdk casks will remove the shared runtime dependencies, so you'll need to reinstall the particular version cask you want from this tap again for the `dotnet` command to work again.
```

* run `sudo dotnet workload clean`

**Output:**
``` 
Unhandled exception: System.IO.FileNotFoundException: Workload version 8.0.401-baseline.24412.2 was not found.
   at Microsoft.NET.Sdk.WorkloadManifestReader.SdkDirectoryWorkloadManifestProvider.RefreshWorkloadManifests()
   at Microsoft.NET.Sdk.WorkloadManifestReader.SdkDirectoryWorkloadManifestProvider..ctor(String sdkRootPath, String sdkVersion, Func`2 getEnvironmentVariable, String userProfileDir, String globalJsonPath, String workloadSetVersion)
   at Microsoft.NET.Sdk.WorkloadManifestReader.SdkDirectoryWorkloadManifestProvider.ForWorkloadSet(String sdkRootPath, String sdkVersion, String userProfileDir, String workloadSetVersion)
   at Microsoft.DotNet.Workloads.Workload.Install.WorkloadResolverFactory.CreateForWorkloadSet(String dotnetPath, String sdkVersion, String userProfileDir, String workloadSetVersion)
   at Microsoft.DotNet.Workloads.Workload.Install.WorkloadGarbageCollector.GarbageCollectWorkloadManifestsAndPacks()
   at Microsoft.DotNet.Workloads.Workload.Install.FileBasedInstaller.GarbageCollect(Func`2 getResolverForWorkloadSet, Nullable`1 offlineCache, Boolean cleanAllPacks)
   at Microsoft.DotNet.Workloads.Workload.Clean.WorkloadCleanCommand.ExecuteGarbageCollection()
   at Microsoft.DotNet.Cli.WorkloadCleanCommandParser.<>c.<ConstructCommand>b__3_0(ParseResult parseResult)
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
```

**Comment by seanlin816** [comment]
having the same issue too. on macOs

**Comment by marcpopMSFT** [comment]
@lewing is there an issue with the wasm workload in 8.0.8? For all others, those warnings in the CLI will go away in 8.0.403 and they should not impact the behavior of install (other than it looks like clean is impacted)
```
/usr/local/share/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/8.0.8/Sdk/WasmApp.Native.targets(366,5): error :   File "/usr/local/share/dotnet/packs/Microsoft.NET.Runtime.Emscripten.3.1.34.Sdk.osx-x64/8.0.8/tools/emscripten/tools/cache.py", line 151, in get [redacted.csproj]
/usr/local/share/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/8.0.8/Sdk/WasmApp.Native.targets(366,5): error :     raise Exception(f'FROZEN_CACHE is set, but cache file is missing: "{shortname}" (in cache root path "{cachedir}")') [redacted.csproj]
/usr/local/share/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/8.0.8/Sdk/WasmApp.Native.targets(366,5): error : Exception: FROZEN_CACHE is set, but cache file is missing: "sysroot_install.stamp" 
```

**Comment by esrahat** [comment]
I fixed the problem by downloading .net 9 preview version of the .net sdk , uninstalled the 8.0.402 version and installed the new one.

**Comment by oakad** [comment]
I, personally, am on 9.0.109 and wasm-tools are still broken for me. In fact, I don't recollect I've ever seen a working wasm-tools install on macos/homebrew.

Which is a pity.
