### ISSUE TITLE
[NETSDKE2E]With NET9 RC2 SDK installed, some strings are unlocalized in output of "dotnet workload --info".

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#43533]
Repro
1.install NET9 RC2 SDK on Loc windows OS. e.g Chinese/German
2. dotnet workload install aspire
3. Dotnet workload config --update-mode workload-set
4. dotnet workload --info

Expected Result:
In Step4， the output are displayed well

Actual Result:
Some strings are unlocalized

Chinese:
![image](https://github.com/user-attachments/assets/69fc9937-4fa6-4b71-8a22-b8ccf791cb4f)

dotnet --info:
.NET SDK:
Version: 9.0.100-rc.2.24467.36
Commit: https://github.com/dotnet/sdk/commit/4d4e5761c3066cba0df0d904b81a1a0a3fc44a88
Workload version: 9.0.100-manifests.47de87af
MSBuild version: 17.12.0-preview-24466-06+be6149fc8

运行时环境:
OS Name: Windows
OS Version: 10.0.22621
OS Platform: Windows
RID: win-x64
Base Path: C:\Program Files\dotnet\sdk\9.0.100-rc.2.24467.36\

已安装 .NET 工作负载:
没有要显示的已安装工作负载。
配置为在安装新清单时使用 workload sets。
Workloads are configured to install and update using workload versions, but none were found. Run "dotnet workload restore" to install a workload version.

Host:
Version: 9.0.0-rc.2.24463.7
Architecture: x64
Commit: static

.NET SDKs installed:
9.0.100-rc.2.24467.36 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
Microsoft.AspNetCore.App 9.0.0-rtm.24466.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 9.0.0-rc.2.24463.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 9.0.0-rtm.24467.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
None

Environment variables:
Not set

global.json file:
Not found

Learn more:
https://aka.ms/dotnet/info

Download .NET:
https://aka.ms/dotnet/download

**Comment by NicoleWang001** [comment]
This issue is still repro with 9.0.100-rc.2.24474.11
![image](https://github.com/user-attachments/assets/2af79b3d-9278-4358-9b0d-bb7d9f7b44a5)

**Comment by darrenarvin123** [comment]
The issue is still reproducible on 9.0.100-rtm.24503.11
![image](https://github.com/user-attachments/assets/54f40f77-51fa-452c-915d-8ff491ec1d53)

**Comment by voroninp** [comment]
@vdanche , how did you install 9.0.100-rc.2.24467.36 ?

**Comment by vdanche** [comment]
> @vdanche , how did you install 9.0.100-rc.2.24467.36 ?
we get it from the table(https://github.com/dotnet/sdk/blob/main/documentation/package-table.md), currently there is no RC2 branch. Do you need another version of RC2 or only 9.0.100-rc.2.24467.36?

**Comment by voroninp** [comment]
I found out, thanks. For some reason restore script of aspnetcore wasn't installing sdk.

**Comment by vdanche** [comment]
Some strings are fixed on 9.0.100-rtm.24509.28 (runtime-9.0.0-rtm.24503.8), But string "workload version" is unlocalized, is it expected?
Chinese:
![Image](https://github.com/user-attachments/assets/cf4b05d5-211e-4615-acc3-eee404aaf30e)
German:
![Image](https://github.com/user-attachments/assets/2b96e7a7-5548-4f54-a532-6c5954465062)

@baronfel

**Comment by richaverma1** [comment]
@marcpopMSFT the bug is not completely fixed, can you take a look?

**Comment by vdanche** [comment]
currently still happens on 9.0.100 sdk
![Image](https://github.com/user-attachments/assets/89ec981a-e85f-41af-a8c1-8868b273f6cd)

**Comment by vdanche** [comment]
still happens on net10 RC2

<img width="1900" height="235" alt="Image" src="https://github.com/user-attachments/assets/379bf03f-98db-4a04-b2e0-1c9cc82c395d" />

**Comment by vwenchen** [comment]
The issue still repro on 11.0.100-preview.4.26214.103

<img width="707" height="131" alt="Image" src="https://github.com/user-attachments/assets/45212f8f-be8b-4c64-a41c-6d9e996d217d" />

**Comment by v-huiwong** [comment]
Still repro on 11.0.100-rc.2.26458.109
German OS:

<img width="1613" height="187" alt="Image" src="https://github.com/user-attachments/assets/3a46f38b-973c-4e13-bc3b-a810b05f522d" />

Chinese OS:

<img width="697" height="140" alt="Image" src="https://github.com/user-attachments/assets/83f381ea-d839-4a3f-802b-6a00957af701" />
