### ISSUE TITLE
Dotnet publish is ignoring --runtime parameter

### ISSUE THREAD

**Issue by iridin** [dotnet/sdk#46053]
### Describe the bug
Since the SDK 9.0.102 version, publishing a containerized application that is intended for multiple platforms, no longer works.
When specifying `--runtime linux-x64` parameter, I can see that the dll is compiled both for `linux-x64` and `win-x64` platforms, subsequently causing the following error:

> C:\Program Files\dotnet\sdk\9.0.102\Containers\build\Microsoft.NET.Build.Containers.targets(251,5): error :
> BaseImageNotFoundException: The RuntimeIdentifier 'win-x64' is not supported by dotnet/runtime-deps:8.0. The supported RuntimeIdentifiers are linux-x64,linux-arm,linux-arm64

With .NET Core SDK '9.0.101' version and all previous (8.0.x) versions, this worked correctly, compiling only for the specified runtime.

### To Reproduce

Call this command to publish the solution (while having Docker switched to Linux containers):

`dotnet publish XYZ.sln --configuration Release --runtime linux-x64 /t:PublishContainer /nodeReuse:False /p:Configuration=Release /p:GeneratePackageOnBuild=True /p:ContainerRuntimeIdentifier=linux-x64`

Get this output (trimmed for brevity):

> XYZCommon succeeded (5,2s) → src\XYZCommon\bin\Release\net8.0\linux-x64\XYZCommon.dll
>  XYZCommon succeeded (0,1s) → src\XYZCommon\bin\Release\net8.0\linux-x64\XYZCommon.dll
>  XYZCommon succeeded (0,4s) → src\XYZCommon\bin\Release\net8.0\linux-x64\XYZCommon.dll
>  XYZCommon succeeded (0,2s) → src\XYZCommon\bin\Release\net8.0\linux-x64\XYZCommon.dll
>  XYZCommon succeeded (3,3s) → src\XYZCommon\bin\Release\net8.0\win-x64\XYZCommon.dll
>  XYZCommon succeeded (1,7s) → src\XYZCommon\bin\Release\net8.0\win-x64\XYZCommon.dll
> XYZ failed with 1 error(s) (4,1s) → Release\win-x64\XYZ\
>   C:\Program Files\dotnet\sdk\9.0.102\Containers\build\Microsoft.NET.Build.Containers.targets(251,5): error :
>        BaseImageNotFoundException: The RuntimeIdentifier 'win-x64' is not supported by dotnet/runtime-deps:8.0. The supported RuntimeIdentifiers are linux-x64,linux-arm,linux-arm64

### Further technical details
- `dotnet --info`

>  .NET SDK:
>  Version:           9.0.102
>  Commit:            cb83cd4923
>  Workload version:  9.0.100-manifests.4a54b1a6
>  MSBuild version:   17.12.18+ed8c6aec5
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.22631
>  OS Platform: Windows
>  RID:         win-x64
>  Base Path:   C:\Program Files\dotnet\sdk\9.0.102\
> 
> .NET workloads installed:
>  [ios]
>    Installation Source: VS 17.12.35707.178
>    Manifest Version:    18.1.9163/9.0.100
>    Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100\microsoft.net.sdk.ios\18.1.9163\WorkloadManifest.json
>    Install Type:              Msi
> 
>  [android]
>    Installation Source: VS 17.12.35707.178
>    Manifest Version:    35.0.7/9.0.100
>    Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100\microsoft.net.sdk.android\35.0.7\WorkloadManifest.json
>    Install Type:              Msi
> 
>  [maccatalyst]
>    Installation Source: VS 17.12.35707.178
>    Manifest Version:    18.1.9163/9.0.100
>    Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100\microsoft.net.sdk.maccatalyst\18.1.9163\WorkloadManifest.json
>    Install Type:              Msi
> 
>  [aspire]
>    Installation Source: VS 17.12.35707.178
>    Manifest Version:    8.2.2/8.0.100
>    Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.2.2\WorkloadManifest.json
>    Install Type:              Msi
> 
>  [maui-windows]
>    Installation Source: VS 17.12.35707.178
>    Manifest Version:    9.0.14/9.0.100
>    Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100\microsoft.net.sdk.maui\9.0.14\WorkloadManifest.json
>    Install Type:              Msi
> 
> Configured to use loose manifests when installing new manifests.
> 
> Host:
>   Version:      9.0.1
>   Architecture: x64
>   Commit:       c8acea2262
> 
> .NET SDKs installed:
>   6.0.428 [C:\Program Files\dotnet\sdk]
>   8.0.404 [C:\Program Files\dotnet\sdk]
>   9.0.102 [C:\Program Files\dotnet\sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 8.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 9.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 8.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 9.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 8.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 9.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
> 
> Other architectures found:
>   x86   [C:\Program Files (x86)\dotnet]
>     registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]
> 
> Environment variables:
>   Not set
> 
> global.json file:
>   Not found

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

> Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
> Version 17.12.4

**Comment by iridin** [comment]
This issue might be connected with this one https://github.com/dotnet/sdk/issues/46015 , but I'm not sure.

**Comment by baronfel** [comment]
@iridin do you have a sample project that reproduces the error, or an https://aka.ms/binlog that you are comfortable sharing? That would let us see more directly what's going on. One immediate question I have is if you have `win-x64` in your `RuntimeIdentifiers` or `ContainerRuntimeIdentifiers` at all.

**Comment by baronfel** [comment]
should be fixed by https://github.com/dotnet/sdk/pull/46067

**Comment by iridin** [comment]
Thank you @baronfel for your quick response and for the fix you devised.
I was trying to create a sample project with the same build logic without all the production code, but I still don't have it ready.
We are building using the fake build script and thus we have the bin logging disabled and the build process is quite complex.

**Comment by baronfel** [comment]
Instead of having to modify your FAKE script, you can set [a few environment variables](https://github.com/dotnet/msbuild/blob/main/documentation/wiki/Providing-Binary-Logs.md#capturing-logs-for-all-msbuild-invocations) and MSBuild itself will create the binlogs for you, if that's easier.

**Comment by baronfel** [comment]
Yes, I think you would 100% be impacted by the bugs fixed in #46067 - your `RuntimeIdentifier` selection is not being correctly honored by our targets.

**Comment by baronfel** [comment]
Going to close this now that we've merged a fix. Look for it to ship in the February SDK servicing releases.

**Comment by iridin** [comment]
Thank you @baronfel for a swift fix.

**Comment by michalkovy** [comment]
I have just tested daily SDK build https://ci.dot.net/public/Sdk/9.0.103-servicing.25065.25/dotnet-sdk-9.0.103-win-x64.exe and I still see the issue. Is 9.0.103-servicing.25065.25 version expected to have the fix? Where can I find a preview/daily build of the SDK with the fix? Thanks

**Comment by baronfel** [comment]
@michalkovy the change has made it to the [release/9.0.1xx](https://github.com/dotnet/sdk/blob/release/9.0.1xx/src/Containers/packaging/build/Microsoft.NET.Build.Containers.targets) branch, my suspicion is that the nightly releases aren't being updated because most servicing releases are handled 'internally' after each quarter's release.

I'll follow up on this and confirm.

**Comment by baronfel** [comment]
I confirmed that the internal builds do have the change. I can't provide those to you at this time, but you can emulate the change by copying the content of the file that I linked to above to the `<SDK install root>\sdk\<version>\Containers\build` location of your SDK installation.

**Comment by reedptaylor** [comment]
@baronfel
I am still getting this error on dotnet SDK 4.0.406. Here is our publish command:
```sh
dotnet restore --locked-mode
...
dotnet publish --no-restore --self-contained --os linux --arch x64 -p ContainerRegistry=XXXXXXX-p ContainerImageTags=XXXXX /t:PublishContainer /p:Version=XXXXXXX
```

Error message:
> /opt/.dotnet/sdk/8.0.406/Containers/build/Microsoft.NET.Build.Containers.targets(252,5): error : BaseImageNotFoundException: The RuntimeIdentifier 'win-x64' is not supported by dotnet/runtime-deps:8.0. The supported RuntimeIdentifiers are linux-x64,linux-arm,linux-arm64 [XXXXXXXXXXXX.csproj]

This flow is still working with dotnet SDK 4.0.404

**Comment by baronfel** [comment]
@reedptaylor I'll need to see a binlog to diagnose this with any degree of accuracy. Can you please collect one via the instructions at https://aka.ms/binlog for review?

**Comment by reedptaylor** [comment]
[binlog.zip](https://github.com/user-attachments/files/19060749/binlog.zip)

**Comment by baronfel** [comment]
@reedptaylor this issue will be fixed in this month's servicing release - it's a slightly different presentation of the same root problem reported in this issue.

**Comment by reedptaylor** [comment]
Perfect, thank you!

**Comment by baronfel** [comment]
@achalrajpoot1 sorry for the delayed response. At the time you commented the 2xx SDKs were no longer in support and so likely did not get the fix. Please use an in support SDK in the 9.0.1xx or 9.0.3xx bands and see if that's got you cleared up.
