### ISSUE TITLE
Build fail after update to latest RC2/RC Refresh

### ISSUE THREAD

**Issue by galvesribeiro** [dotnet/sdk#482]
As requested by @morrisjoe 

I previously created this issue: https://github.com/dotnet/coreclr/issues/8602

Basically build works if you use `dotnet` cli only. When using Visual Studio 2017 (besides it crash a lot) it fail to build and multitarget is not working...

To reproduce:

1. `dotnet new` -> Any console app build fail with the error in the previously mentioned issue while building from VS2017
2. You can check our "updated/simplified" csproj by trying to build https://github.com/galvesribeiro/orleans/blob/codegen-core/vNext/src/ClientGenerator/ClientGenerator.csproj 

The error is basically:

```
1>------ Build started: Project: ConsoleApp2, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(127,7): error MSB4131: The "FilesWritten" parameter is not supported by the "GenerateRuntimeConfigurationFiles" task. Verify the parameter exists on the task, and it is a gettable public instance property.
1>Done building project "ConsoleApp2.csproj" -- FAILED.
========== Build: 0 succeeded or up-to-date, 1 failed, 0 skipped ==========
```

**Comment by srivatsn** [comment]
This sounds like a mismatch in the version of the SDK task. Is a msbuild process from the previous install still running maybe (msbuild hangs around for a bit in case it needs to build again). Another possibility is that in your project you have some project references. Have all those project refs been converted to SDK form as well. Specifically if those proejcts still have a PackageReference to Microsoft.NET.Sdk then that could explain the mismatch.

**Comment by galvesribeiro** [comment]
@srivatsn I can check all our projects in Orleans. However, like I said, that happens with brand new project created by `dotnet new`.

Regarding msbuild instances, I think it is not possible since right after the update of VS2017, it asked me to reboot, and I did it.

Again, lets ignore Orleans project for now... A simple `dotnet new`, `dotnet build` works perfectly but if I try to build the project on VS2017, that error happens.

**Comment by rainersigwald** [comment]
Can you build from the command line in a developer command prompt using msbuild (instead of dotnet)?

**Comment by galvesribeiro** [comment]
Yeah, from the command line it build fine using MSBuild. However from VS2017 same problem :(

![image](https://cloud.githubusercontent.com/assets/4714040/21123604/defa6d72-c0c0-11e6-89c3-840bb5a65a35.png)

**Comment by piotrpMSFT** [comment]
@galvesribeiro I see you have two projects. Are they both new? Do both include a `<Project Sdk="...">` attribute?

**Comment by galvesribeiro** [comment]
Just to be sure:

```
<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="**\*.cs" />
    <EmbeddedResource Include="**\*.resx" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETCore.App" Version="1.0.1" />
  </ItemGroup>

</Project>
```

Ignore the class library, I was just testing if that problem happens as well with a class library but no, it doesn't. It only happen with VS2017 and Console App projects... I also tried to update to `netcoreapp1.1` but it still the same problem...

**Comment by piotrpMSFT** [comment]
To recap:
- VS2017: issue
- CLI: no issue
- MSBuild: no issue

**Comment by galvesribeiro** [comment]
Yup! If you need to debug with me on my machine I can share my screen in a skype for business session if you want but like I said, it is very specific to VS2017 + Console App.

Class library, CLI, MSBuild, VSCode, all that work just fine (even with Console Apps).

**Comment by srivatsn** [comment]
@dsplaisted can you take a look at this with @galvesribeiro?

**Comment by dsplaisted** [comment]
@galvesribeiro Can you send me an email at daplaist at microsoft.com so we can get connected on Skype and debug this?

**Comment by galvesribeiro** [comment]
Sorry @dsplaisted ot was late yesterday. I'm adding your alias on SfB so we can talk there.

**Comment by harshjain2** [comment]
+1 on this issue. 
I'm also facing this issue.

**Comment by dsplaisted** [comment]
This happens when there are MSBuild processes running that have loaded the tasks from the earlier version of the .NET SDK.  If you kill all MSBuild.exe processes that are running, this should fix the issue.

**Comment by galvesribeiro** [comment]
Yep, looks like this is indeed the problem. I'll keep watching this.

For now, I'm closing the issue. In case we hit it again for other steps I'll ping you guys here.

Thank you for the support.

**Comment by JustinRChou** [comment]
I am still having this issue with a new xUnit test project that I added to my web project after the 12/12 update.

**Comment by joacar** [comment]
Experience this issue as well and killing all msbuild process (`taskkill /F /IM msbuild.exe`) doesn't help me. Run the project successfully for 30 minutes ago...

**Comment by joacar** [comment]
The new project format doesn't work at all with Visual Studio preview for Mac. Now both development environments are out of the game.

**Comment by galvesribeiro** [comment]
More one issue #493

**Comment by Ziflin** [comment]
I'm still getting this error:
>Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4131	The "FilesWritten" parameter is not supported by the "GenerateRuntimeConfigurationFiles" task. Verify the parameter exists on the task, and it is a gettable public instance property.	MyApp	D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets	127	

It oddly comes and goes. I have the latest VS2017 RC and I was profiling some code (building multiple times over and over) and after about 20 recompiles the error appeared. VS2017 had focus the entire time, it just started reporting this error and will no longer compile until I exit VS2017 and restart it. 

This is the 2nd time in the last few hours that I've had it happen and it did not happen until the last update.

I have a *minimal* .NET Core Console App referencing a .NET Core Library and I'm running the App with a combination of "Start Without Debugging" and "Start Debugging" if that helps.

**Comment by Ziflin** [comment]
I *think* I've fixed my issues. There was a UnitTest project using the older xml project style. After updating it to the new style it seems to be compiling properly again.

**Comment by lostmsu** [comment]
@galvesribeiro , please, reopen the bug. My machine does not have older MSBuild processes running, but I get the same error with a new .NET Core Empty Web Site.

**Comment by Roblinde** [comment]
I just ran into this issue as well for an asp.net core application. I managed to fix it by changing the SDK property to this:

`<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">`

This gave me errors about no entry point for application. Then I changed it back to:

`<Project Sdk="Microsoft.NET.Sdk.Web" ToolsVersion="15.0">` 

and suddenly it started working again.

**Comment by galvesribeiro** [comment]
@Roblinde I'm with this precise error here https://github.com/dotnet/sdk/issues/493

No matter if I change the Sdk on project root...

**Comment by ssinno28** [comment]
I had this issue, basically I had other projects with different MSBuild Tools versions. Make sure all of your projects in your solution have the new Sdk="" syntax for setting the tools and taht they are the same version and you should be good.

**Comment by sumitkute** [comment]
I am also facing the same issue. I changed to <Project Sdk="Microsoft.NET.Sdk.Web" ToolsVersion="15.0">
but no luck. It is using the target at location Also C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn
