### ISSUE TITLE
EnableWindowsTargeting is broken in .NET 10 Preview 4 (Microsoft.WindowsDesktop.App.Ref not found)

### ISSUE THREAD

**Issue by mus65** [dotnet/sdk#48949]
### Describe the bug

After updating from .NET 10 Preview 3 to Preview 4, a simple project with `<EnableWindowsTargeting>true</EnableWindowsTargeting>` can not be built on Linux:

```
error NU1102:
      Unable to find package Microsoft.WindowsDesktop.App.Ref with version (= 10.0.0-preview.4.25258.1)
        - Found 140 version(s) in nuget.org [ Nearest version: 10.0.0-preview.4.25258.110 ]
```

### To Reproduce

- Create a new project with `dotnet new console` with .NET 10 Preview 4 on Linux
- add `<EnableWindowsTargeting>true</EnableWindowsTargeting>` to csproj file
- run `dotnet build`

### Exceptions (if any)

```
error NU1102:
      Unable to find package Microsoft.WindowsDesktop.App.Ref with version (= 10.0.0-preview.4.25258.1)
        - Found 140 version(s) in nuget.org [ Nearest version: 10.0.0-preview.4.25258.110 ]
```

### Further technical details
Output of `dotnet --info`:

```
.NET SDK:
 Version:           10.0.100-preview.4.25258.110
 Commit:            c22dcd0c7a
 Workload version:  10.0.100-manifests.9773070f
 MSBuild version:   17.15.0-preview-25258-110+c22dcd0c7

Runtime Environment:
 OS Name:     fedora
 OS Version:  41
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /home/user/.dotnet/sdk/10.0.100-preview.4.25258.110/

.NET workloads installed:
There are no installed workloads to display.
Configured to use workload sets when installing new manifests.
Workloads are configured to install and update using workload versions, but none were found. Run "dotnet workload restore" to install a workload version.

Host:
  Version:      10.0.0-preview.4.25258.110
  Architecture: x64
  Commit:       c22dcd0c7a

.NET SDKs installed:
  9.0.202 [/home/user/.dotnet/sdk]
  10.0.100-preview.4.25258.110 [/home/user/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.3 [/home/user/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 10.0.0-preview.4.25258.110 [/home/user/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.3 [/home/user/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 10.0.0-preview.4.25258.110 [/home/user/.dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/home/user/.dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by jeromelaban** [comment]
This issue still happens with Preview 5

**Comment by baronfel** [comment]
Triage: @mmitche I'm worried that there may be a syncronization issue in the VMR for this package. 

The SDK p5 version from eng/Version.props is **10.0.0-preview.5.25280.105**.
The VMR p5 version from src/sdk/eng/Versions.props is **10.0.0-preview.5.25265.101**

Neither of these matches the version pushed to Nuget.org for p5, which is [10.0.0-preview.5.25277.114](https://www.nuget.org/packages/Microsoft.WindowsDesktop.App.Ref/10.0.0-preview.5.25277.114).

Who should pick this up?

**Comment by mmitche** [comment]
UB should. This looks like the property used to determine the WD version is not being correctly set.

The version in sdk's eng/Versions.props would not be the version. It should be the live version flowing from WD.

**Comment by mmitche** [comment]
This is a join point issue. We build the SDK archive in each vertical in pass 1, on each OS. On non-Windows platforms, we can't build the windowsdesktop assets of course, so these values just end up as whatever was in eng/sdk/Versions.props.

This is fixable, because UB unifies all the version numbers across all the runtimes. So, we could substitute in the runtime shared framework version number, and everything will work. Not my favorite solution, tbh, but IMO it's much much worse to move the sdk building into pass2

**Comment by mmitche** [comment]
https://github.com/dotnet/sdk/pull/49722

**Comment by mmitche** [comment]
In addition to this, the Windows SDK is actually included in non-Windows SDKs. This needs to be resolved

**Comment by mmitche** [comment]
This particular issue should be fixed, opening another in its place for the SDK.

**Comment by mus65** [comment]
@mmitche still happening with preview 6. I assume the fix just didn't make it into preview 6 and it will be fixed in preview 7?

```
Unable to find package Microsoft.WindowsDesktop.App.Ref with version (= 10.0.0-preview.6.25315.102)
        - Found 146 version(s) in nuget.org [ Nearest version: 10.0.0-preview.6.25358.103 ]
```

**Comment by akoeplinger** [comment]
Yes it's not in preview 6.
