### ISSUE TITLE
The link present on the installation window are not accessible with any keyboard keys: A11y_.NET SDK and CLI_Uninstall the SDK_Keyboard.

### ISSUE THREAD

**Issue by shindepra** [dotnet/sdk#50658]
### Github tags:
#A11yMAS; #A11ySev1; #A11yTCS; #Benchmark; #GH_.NETSDkandCLI_Win32_Sept2025; #.NET SDK and CLI; #DesktopApp; #Win32; #WCAG2.1.1; #Keyboard; #AILimited

### Environment and OS Details:
App name: .NET SDK and CLI
NET 9.0 SDK (v9.0.304) - Windows x64 Installer
Windows 11 Enterprise Version 24H2(OS Build 26100.5074)

### Repro Steps:

1. Install the application till successfully installed window. 
2. Observe that The link present on the installation window are not accessible with any keyboard keys.

### Actual:
The "Uninstall Successfully Completed" status message is not announced by the screen reader when uninstalling the .NET 9.0 SDK.
Issue is also observed with other screen Readers.

### Expected Result:
The screen reader should announce the "Uninstall Successfully Completed" message once the process finishes.

### User Impact:
Keyboard users will not be able to access the data present on the installer window and can miss the important information.

### Attachments:

https://github.com/user-attachments/assets/c84f8f47-0667-4a0c-a347-26a8dbec1135

**Comment by kupatkar99** [comment]
@marcpopMSFT , @joeloff Could you please Confirm us on which version issue is fixed.

**Comment by marcpopMSFT** [comment]
It should be resolved in RC2 so once there are builds for testing there, try that out.

**Comment by PoojaNamde** [comment]
@marcpopMSFT Verified the issue in Microsoft .NET SDK 9.0.305, Issue is still reproducing as we are not able to access the links with keyboard.

Please share the environment where the issue is fixed. Also please do not close this bug. This bug should only be closed by Trusted Tester after verification.

**Comment by marcpopMSFT** [comment]
Accessibility testing only applies to net10 as prior to that, we were using WiX 3.1 which didn't have good accessibility support. This is fixed in RC2 which is an internal release. I'll defer to @merriemcgaw on whether that can be shared or you have to wait for the RC2 public release to retest.

**Comment by kupatkar99** [comment]
#Closed;
