### ISSUE TITLE
Error "MSB4018: The "ProcessFrameworkReferences" task failed unexpectedly." happens when publish NPE project in CLI.

### ISSUE THREAD

**Issue by vwenchen** [dotnet/sdk#50674]
### REGRESSION INFO
Worked well on .NET 10 RC1

### To Reproduce
Clean machine: Windows 11-x64 (24H2)
1. Install .NET 10 RC2 SDK (10.0.100-rc.1.25451.107)
2. Download sln from: https://github.com/NuGetPackageExplorer/NuGetPackageExplorer
3. Build sln in CLI, `dotnet publish -c Release -r win-x64 /p:PublishReadyToRun=true /p:SelfContained=true NuGetPackageExplorer.csproj`

### ACTUAL
Error: "MSB4018: The "ProcessFrameworkReferences" task failed unexpectedly." happens 

<img width="551" height="155" alt="Image" src="https://github.com/user-attachments/assets/896b2344-9dc5-40f9-974d-078b59a39a67" />

### EXPECTED
Build sln successfully

Dotnet --info
.NET SDK:
 Version:           10.0.100-rc.2.25457.102
 Commit:            8ea69c337b
 Workload version:  10.0.100-manifests.0e7bb24e
 MSBuild version:   17.15.0-preview-25457-102+8ea69c337

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.26100
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\10.0.100-rc.2.25457.102\

.NET workloads installed:
There are no installed workloads to display.
Configured to use workload sets when installing new manifests.
No workload sets are installed. Run "dotnet workload restore" to install a workload set.

Host:
  Version:      10.0.0-rc.2.25457.102
  Architecture: x64
  Commit:       8ea69c337b

.NET SDKs installed:
  10.0.100-rc.2.25457.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 10.0.0-rc.2.25457.102 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 10.0.0-rc.2.25457.102 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 10.0.0-rc.2.25457.102 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by marcpopMSFT** [comment]
Weird given that this code was written in April. Not sure why it's showing up now. @dsplaisted

**Comment by baronfel** [comment]
@marcpopMSFT I just fixed this in  https://github.com/dotnet/sdk/pull/50682 for RC2+, did the original change in https://github.com/dotnet/sdk/pull/50455 make it into RC1?

**Comment by marcpopMSFT** [comment]
It was not in RC1. This was early testing of RC2. Looks like we're good then so resolving.

**Comment by vwenchen** [comment]
@baronfel This issue still repro on .NET 10 RC2 SDK 10.0.100-rc.2.25460.104, can you take a look?

<img width="553" height="157" alt="Image" src="https://github.com/user-attachments/assets/4728fa23-9ac6-46e4-aeab-14d5b95816c4" />

**Comment by baronfel** [comment]
The fix hasn't merged to the VMR yet, so no RC2 builds will have it. EDIT: it did merge, but just an hour ago: https://github.com/dotnet/dotnet/pull/2334. So the next build should be ok.

**Comment by vwenchen** [comment]
Not repro on .NET10 RC2 SDK 10.0.0-rc.2.25462.117 .

<img width="546" height="134" alt="Image" src="https://github.com/user-attachments/assets/bb6aad6e-9cfd-4f8e-b5a2-6324909c8bd8" />
