### ISSUE TITLE
The "ProcessFrameworkReferences" task failed unexpectedly. System.ArgumentNullException: Value cannot be null. (Parameter 'key')

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/sdk#50680]
### Describe the bug

Build fails with:

```
The "ProcessFrameworkReferences" task failed unexpectedly.
System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
   at Microsoft.NET.Build.Tasks.NuGetUtils.GetBestMatchingRidWithExclusion(RuntimeGraph runtimeGraph, String runtimeIdentifier, IEnumerable`1 runtimeIdentifiersToExclude, IEnumerable`1 availableRuntimeIdentifiers, Boolean& wasInGraph)
   at Microsoft.NET.Build.Tasks.ProcessFrameworkReferences.AddToolPack(ToolPackType toolPackType, Version normalizedTargetFrameworkVersion, List`1 packagesToDownload, List`1 implicitPackageReferences)
   at Microsoft.NET.Build.Tasks.ProcessFrameworkReferences.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(TaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
```

### To Reproduce

```shell
git clone https://github.com/dotnet/macios macios
cd macios
git checkout darc-net10.0-3e2d6574-3e2e-4233-aab9-99cf75de33e4
git reset --hard e583c4fe8da7b92c0bc9067d0796ba708401fc8c
make reset
./configure --disable-all-platforms --enable-macos
make all -j8
make install -j8
./builds/downloads/dotnet/dotnet build tests/monotouch-test/dotnet/macOS/monotouch-test.csproj /p:PublishAot=true
```

Binlog: 

[msbuild.binlog.zip](https://github.com/user-attachments/files/22212051/msbuild.binlog.zip)

### Further technical details

This is a regression in .NET 10 RC 2, it's happening in this maestro bump: https://github.com/dotnet/macios/pull/23751

Looks like https://github.com/dotnet/sdk/pull/50455 is recent and in the area, CC @baronfel

**Comment by baronfel** [comment]
Taking a look!

**Comment by premun** [comment]
Looks like a similar thing is happening in https://github.com/dotnet/sdk/pull/50648

**Comment by baronfel** [comment]
This appears to be a simple nullref - this Target doesn't have nullability-checking enabled so it's easy for these to slip through. I've got a more thoroughly-logged and null-checked version that I sent to @rolfbjarne for testing that seems to work - doing a final local build to test and will send a PR shortly.

**Comment by rmarinho** [comment]
MAUI hitting this too.

**Comment by ericstj** [comment]
Just hit this myself using latest RC2 build.

**Comment by baronfel** [comment]
We merged the PR, I think we need VMR codeflow and a new nightly

**Comment by rmarinho** [comment]
I think I m testing the new version from the VMR with this change 10.0.100-rc.2.25460.104

and still see the issue ...

[uitests-apphost-Controls.TestCases.HostApp-Release-Build-dotnet-134020541372487990.binlog.zip](https://github.com/user-attachments/files/22271865/uitests-apphost-Controls.TestCases.HostApp-Release-Build-dotnet-134020541372487990.binlog.zip)
