### ISSUE TITLE
[WebToolsE2E] The version displayed in the SDK installer for .NET 10 GA includes build number info

### ISSUE THREAD

**Issue by EmilyFeng97** [dotnet/sdk#51234]
**Platform**
- [x] Windows
- [ ] macOS
- [ ] Linux

**INSTALL STEPS**
1. Clean Win11 x64 24h2 ENU
1. Install the latest .NET 10.0 GA SDK [build 10.0.100-rtm.25520.106]

**EXPECTED RESULT**
The sdk version for GA should be `10.0.100` in the sdk installer, control panel and File Explorer.

**ACTUAL RESULT**
1. In the installer UI, the sdk version shown is `10.0.100-rtm.25520.106` rather than `10.0.100`

<img width="643" height="486" alt="Image" src="https://github.com/user-attachments/assets/ef8defd0-b532-41c5-bc00-6b991ff907a0" />

<img width="640" height="486" alt="Image" src="https://github.com/user-attachments/assets/0aa3b5bf-4185-433d-82d3-225b11712ceb" />

1. In the control panel, the sdk version shown is `10.0.100-rtm.25520.106` rather than `10.0.100`

<img width="890" height="192" alt="Image" src="https://github.com/user-attachments/assets/35cfe35d-5d04-4845-b274-41db2a4b8f10" />

**OTHER NOTES**

1. Open command prompt, run `dotnet --info`, sdk version is `10.0.100`

   <img width="905" height="597" alt="Image" src="https://github.com/user-attachments/assets/d442c7ad-f793-4ea5-8754-9e0eb6319417" />

1. Open File Explorer and go to `C:\Program Files\dotnet\sdk` folder, the sdk version is `10.0.100`

   <img width="626" height="155" alt="Image" src="https://github.com/user-attachments/assets/28e05796-b9b9-4aec-8d23-b9dd2bf6c177" />

**Comment by balachir** [comment]
@EmilyFeng97 @jinzhao1127 I believe this should be fixed using latest builds for .NET 10 GA. Can you confirm and let me know?

**Comment by vdanche** [comment]
This issue still repro on the latest net10 GA build:10.0.100-rtm.25520.106

<img width="988" height="751" alt="Image" src="https://github.com/user-attachments/assets/6e725bff-d443-43d8-a99b-073a50fedede" />

**Comment by jinzhao1127** [comment]
> [@EmilyFeng97](https://github.com/EmilyFeng97) [@jinzhao1127](https://github.com/jinzhao1127) I believe this should be fixed using latest builds for .NET 10 GA. Can you confirm and let me know?

This issue still reproduce with latest .NET 10.0 GA (10.0.100-rtm.25520.106)

**Comment by EmilyFeng97** [comment]
Verify this issue on the latest SDK 10.0 GA [`10.0.100-rtm.25523.104`], it does not reproduce. Close it as fixed.
cc: @balachir 
<img width="648" height="502" alt="Image" src="https://github.com/user-attachments/assets/fb8cd86b-28ec-4aec-ba2a-14a645f831d0" />

<img width="943" height="554" alt="Image" src="https://github.com/user-attachments/assets/f18b0964-11a6-4f3c-8b68-cd76a9debde0" />
