### ISSUE TITLE
[.NET10RC2] `dotnet watch run --no-hot-reload` fails

### ISSUE THREAD

**Issue by TheArcaneBrony** [dotnet/sdk#51476]
### Describe the bug
Running `dotnet watch run --no-hot-reload` does not work correctly, at least for blazor-wasm projects.
When a rebuild is triggered, it does not shut down the old dev server, causing the new one to fail with a bind error.

### To Reproduce
- Create new blazor wasm app (ie. `dotnet new blazorwasm -e -p --no-https`)
- Run with watch: `dotnet watch run -c Release --property WarningLevel=0 --no-hot-reload`
- Open in browser
- Make a change to one of the .razor files (ie. Home.razor)
- Note that the server fails to start
- Reload the page, note that the browser console is spammed with integrity errors due to not being able to find files.

### Exceptions (if any)
```
fail: Microsoft.Extensions.Hosting.Internal.Host[11]
      Hosting failed to start
      System.IO.IOException: Failed to bind to address http://[::]:5117: address already in use.
       ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use
       ---> System.Net.Sockets.SocketException (98): Address already in use
         at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, Boolean disconnectOnFailure, String callerName)
         at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
         at System.Net.Sockets.Socket.Bind(EndPoint localEP)
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass28_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
         at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__14_1(IHostedService service, CancellationToken token)
         at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
```

### Further technical details
<details><summary>details of dotnet --info</summary>
<p>
```
.NET SDK:
 Version:           10.0.100-rc.2.25502.107
 Commit:            89c8f6a112
 Workload version:  10.0.100-manifests.0cee6f9c
 MSBuild version:   18.0.0-preview-25502-107+89c8f6a11

Runtime Environment:
 OS Name:     nixos
 OS Version:  25.11
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /nix/store/aj7lxjjn3rl2bazsv9p0dfnv069j6rsq-dotnet-sdk-10.0.100-rc.2.25502.107/share/dotnet/sdk/10.0.100-rc.2.25502.107/

.NET workloads installed:
There are no installed workloads to display.
Configured to use workload sets when installing new manifests.
No workload sets are installed. Run "dotnet workload restore" to install a workload set.

Host:
  Version:      10.0.0-rc.2.25502.107
  Architecture: x64
  Commit:       89c8f6a112

.NET SDKs installed:
  10.0.100-rc.2.25502.107 [/nix/store/aj7lxjjn3rl2bazsv9p0dfnv069j6rsq-dotnet-sdk-10.0.100-rc.2.25502.107/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 10.0.0-rc.2.25502.107 [/nix/store/aj7lxjjn3rl2bazsv9p0dfnv069j6rsq-dotnet-sdk-10.0.100-rc.2.25502.107/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 10.0.0-rc.2.25502.107 [/nix/store/aj7lxjjn3rl2bazsv9p0dfnv069j6rsq-dotnet-sdk-10.0.100-rc.2.25502.107/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_CLI_TELEMETRY_OPTOUT              [1]
  DOTNET_WATCH_SUPPRESS_LAUNCH_BROWSER     [1]

global.json file:
  Invalid [/home/Rory/git/matrix/MatrixUtils-master/global.json]
    Version '9.0.0' is not valid for the 'sdk/version' value. SDK feature bands start at 1 - for example, 9.0.100
```
</p>
</details>
- Rider 2025.2.4 on NixOS, though using dotnet CLI to run my project.

**Comment by Youssef1313** [comment]
cc @tmat

**Comment by tmat** [comment]
Likely fixed by https://github.com/dotnet/sdk/pull/50983. Please let us know if it repros in the latest build.

**Comment by mispencer** [comment]
@tmat - this is still reproducible in the latest build. 

This appears to be due to watch immediately sending a SIGKILL after sending SIGTERM and thus probably not giving the killed process enough time to respond to the SIGTERM. 

You can see this in the source watch code that the time between SIGTERM and SIGKILL depends on [the process cleanup timeout](https://github.com/dotnet/sdk/blob/2b9fc02a265c735f2132e4e3626e94962e48bdf5/src/BuiltInTools/dotnet-watch/Process/ProcessRunner.cs#L255) and that, [in no-hot-reload case, the process cleanup timeout defaults to zero.](https://github.com/dotnet/sdk/blob/2b9fc02a265c735f2132e4e3626e94962e48bdf5/src/BuiltInTools/dotnet-watch/CommandLine/EnvironmentOptions.cs#L66)

The process cleanup timeout is overridable by setting the `DOTNET_WATCH_PROCESS_CLEANUP_TIMEOUT_MS` environment variable and, indeed, if you set it to a reasonable number - 100 seems to be enough - then the issue no longer occurs. *This is a valid workaround until this is fixed assuming you are willing to install the latest unstable build.*

I assume setting a short, but not zero, process cleanup timeout default for the no-hot-reload case would be enough to resolve this.

Relevant logs with `DOTNET_WATCH_PROCESS_CLEANUP_TIMEOUT_MS` **unset**.
```
dotnet watch ⌚ Terminating process 70687 (SIGTERM).
dotnet watch ⌚ Terminating process 70687 (SIGKILL).
dotnet watch ⌚ Waiting for process 70687 to exit (1).
```

Relevant logs with `DOTNET_WATCH_PROCESS_CLEANUP_TIMEOUT_MS` **set to 1000**.
```
dotnet watch ⌚ Terminating process 71203 (SIGTERM).
dotnet watch ⌚ Waiting for process 71203 to exit within 1s.
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
dotnet watch ⌚ Terminating process 71203 (SIGKILL).
dotnet watch ⌚ Waiting for process 71203 to exit (1).
```

**Comment by tmat** [comment]
> [in no-hot-reload case, the process cleanup timeout defaults to zero.](https://github.com/dotnet/sdk/blob/2b9fc02a265c735f2132e4e3626e94962e48bdf5/src/BuiltInTools/dotnet-watch/CommandLine/EnvironmentOptions.cs#L66)

That's certainly a bug. Thanks for the details.

**Comment by qwadrox** [comment]
It is causing a significant regression in local development productivity. In a multi-service ASP.NET Core environment, I have to manually track down and restart multiple backend APIs because of this. Hot reload is not workaround for me, some changes require a full backend restart. 

Steps to reproduce:

1.
```sh
dotnet new webapi -n MyProjectNameTest -f net10.0
```

3. Start the app with:

```sh
dotnet watch --no-hot-reload
```

2. Edit summaries array in the WeatherForecast sample. 

Details: 

<details><summary>dotnet --info</summary>
<p>

```sh
 MyProjectNameTest dotnet --info
.NET SDK:
 Version:           10.0.102
 Commit:            4452502459
 Workload version:  10.0.100-manifests.73000c7b
 MSBuild version:   18.0.7+445250245

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  26.1
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /Users/borosmate/Library/Application Support/dnvm/dn/sdk/10.0.102/

.NET workloads installed:
There are no installed workloads to display.
Configured to use workload sets when installing new manifests.
No workload sets are installed. Run "dotnet workload restore" to install a workload set.

Host:
  Version:      10.0.2
  Architecture: arm64
  Commit:       4452502459

.NET SDKs installed:
  6.0.428 [/Users/borosmate/Library/Application Support/dnvm/dn/sdk]
  8.0.411 [/Users/borosmate/Library/Application Support/dnvm/dn/sdk]
  9.0.301 [/Users/borosmate/Library/Application Support/dnvm/dn/sdk]
  9.0.308 [/Users/borosmate/Library/Application Support/dnvm/dn/sdk]
  10.0.100-preview.5.25277.114 [/Users/borosmate/Library/Application Support/dnvm/dn/sdk]
  10.0.102 [/Users/borosmate/Library/Application Support/dnvm/dn/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.36 [/Users/borosmate/Library/Application Support/dnvm/dn/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.17 [/Users/borosmate/Library/Application Support/dnvm/dn/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.6 [/Users/borosmate/Library/Application Support/dnvm/dn/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.11 [/Users/borosmate/Library/Application Support/dnvm/dn/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 10.0.0-preview.5.25277.114 [/Users/borosmate/Library/Application Support/dnvm/dn/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 10.0.2 [/Users/borosmate/Library/Application Support/dnvm/dn/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.36 [/Users/borosmate/Library/Application Support/dnvm/dn/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.17 [/Users/borosmate/Library/Application Support/dnvm/dn/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.6 [/Users/borosmate/Library/Application Support/dnvm/dn/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.11 [/Users/borosmate/Library/Application Support/dnvm/dn/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 10.0.0-preview.5.25277.114 [/Users/borosmate/Library/Application Support/dnvm/dn/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 10.0.2 [/Users/borosmate/Library/Application Support/dnvm/dn/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT                              [/Users/borosmate/Library/Application Support/dnvm/dn]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

</p>
</details> 


<details><summary>watch with--verbose</summary>
<p>

```sh
dotnet watch --no-hot-reload --verbose
dotnet watch ⌚ Working directory: '/Users/borosmate/Documents/Playground/MyProjectNameTest'
dotnet watch ⌚ Hot Reload disabled by command line switch.
dotnet watch ⌚ Evaluating dotnet-watch file set.
dotnet watch 🔨 Running MSBuild target 'GenerateWatchList' on '/Users/borosmate/Documents/Playground/MyProjectNameTest/MyProjectNameTest.csproj'
dotnet watch 🚀 Launched '/Users/borosmate/Library/Application Support/dnvm/dn/dotnet' with arguments 'msbuild /restore /nologo /v:m /Users/borosmate/Documents/Playground/MyProjectNameTest/MyProjectNameTest.csproj /t:GenerateWatchList --property:NuGetInteractive=true /p:_DotNetWatchListFile=/var/folders/sn/y8czhy0d39s_pdc34grtsty00000gn/T/tmpFzExiA.tmp /p:DotNetWatchBuild=true /p:DesignTimeBuild=true "/p:CustomAfterMicrosoftCommonTargets=/Users/borosmate/Library/Application Support/dnvm/dn/sdk/10.0.102/DotnetTools/dotnet-watch/10.0.102/tools/net10.0/any/DotNetWatch.targets" "/p:CustomAfterMicrosoftCommonCrossTargetingTargets=/Users/borosmate/Library/Application Support/dnvm/dn/sdk/10.0.102/DotnetTools/dotnet-watch/10.0.102/tools/net10.0/any/DotNetWatch.targets"': process id 93804
dotnet watch ⌚ Process id 93804 ran for 1232ms and exited with exit code 0.
dotnet watch 🔨   Determining projects to restore...
dotnet watch 🔨   All projects are up-to-date for restore.
dotnet watch ⌚ Watching 2 file(s) for changes
dotnet watch ⌚ Application kind: WebApplication.
dotnet watch 🔃 [MyProjectNameTest (net10.0)] Using browser-refresh middleware
dotnet watch 🔃 [MyProjectNameTest (net10.0)] Refresh server running at wss://localhost:50259,ws://localhost:50260.
dotnet watch ⌚ launchSettings does not allow launching browsers.
dotnet watch 🚀 Launched '/Users/borosmate/Library/Application Support/dnvm/dn/dotnet' with arguments 'run': process id 93946
dotnet watch ⌚ Waiting for changes
Using launch settings from /Users/borosmate/Documents/Playground/MyProjectNameTest/Properties/launchSettings.json...
Building...
csproj                                                                                                           (0.5s)
dotnet watch ⌚ [FW] Updated '/Users/borosmate/Documents/Playground/MyProjectNameTest/obj/Debug/net10.0/rjsmrazor.dswa.cache.json'.
dbug: Microsoft.AspNetCore.Watch.BrowserRefresh.BlazorWasmHotReloadMiddleware[0]
      Middleware loaded
dbug: Microsoft.AspNetCore.Watch.BrowserRefresh.BrowserScriptMiddleware[0]
      Middleware loaded. Script /_framework/aspnetcore-browser-refresh.js (16152 B).
dbug: Microsoft.AspNetCore.Watch.BrowserRefresh.BrowserScriptMiddleware[0]
      Middleware loaded. Script /_framework/blazor-hotreload.js (776 B).
dbug: Microsoft.AspNetCore.Watch.BrowserRefresh.BrowserRefreshMiddleware[0]
      Middleware loaded: DOTNET_MODIFIABLE_ASSEMBLIES=(null), __ASPNETCORE_BROWSER_TOOLS=true
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5067
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /Users/borosmate/Documents/Playground/MyProjectNameTest
dotnet watch ⌚ [FW] Updated '/Users/borosmate/Documents/Playground/MyProjectNameTest/Program.cs'.
dotnet watch ⌚ Terminating process 93946 (SIGTERM).
dotnet watch ⌚ Terminating process 93946 (SIGKILL).
dotnet watch ⌚ Waiting for process 93946 to exit (1).
dotnet watch ⌚ Process id 93946 ran for 6006ms and exited with exit code 137.
dotnet watch ❌ Exited with error code 137
dotnet watch ⌚ File changed: /Users/borosmate/Documents/Playground/MyProjectNameTest/Program.cs
dotnet watch ⌚ Modifying command to use --no-restore
dotnet watch ⌚ Application kind: WebApplication.
dotnet watch ⌚ launchSettings does not allow launching browsers.
dotnet watch 🚀 Launched '/Users/borosmate/Library/Application Support/dnvm/dn/dotnet' with arguments 'run --no-restore': process id 94297
dotnet watch ⌚ Waiting for changes
Using launch settings from /Users/borosmate/Documents/Playground/MyProjectNameTest/Properties/launchSettings.json...
Building...
  MyProjectNameTest net10.0                                                                          CoreCompile (2.7s)
dotnet watch ⌚ [FW] Updated '/Users/borosmate/Documents/Playground/MyProjectNameTest/obj/Debug/net10.0/MyProjectNameTest.dll'.
dotnet watch ⌚ [FW] Updated '/Users/borosmate/Documents/Playground/MyProjectNameTest/obj/Debug/net10.0/MyProject(2.7s)st.pdb'.
dotnet watch ⌚ [FW] Updated '/Users/borosmate/Documents/Playground/MyProjectNameTest/obj/Debug/net10.0/MyProjectNameTest.dll'.
dotnet watch ⌚ [FW] Updated '/Users/borosmate/Documents/Playground/MyProjectNameTest/obj/Debug/net10.0/refint/MyProjectNameTest.dll'.
dotnet watch ⌚ [FW] Updated '/Users/borosmate/Documents/Playground/MyProjectNameTest/obj/Debug/net10.0/MyProjectNameTest.pdb'.
dotnet watch ⌚ [FW] Deleted '/Users/borosmate/Documents/Playground/MyProjectNameTest/obj/Debug/net10.0/apphost'.
dotnet watch ⌚ [FW] Updated '/Users/borosmate/Documents/Playground/MyProjectNameTest/obj/Debug/net10.0/apphost'.
  MyProjectNameTest net10.0                                                       ResolveJSModuleStaticWebAssets (2.7s)
dotnet watch ⌚ [FW] Updated '/Users/borosmate/Documents/Playground/MyProjectNameTest/obj/Debug/net10.0/rjsmrazor.dswa.cache.json'.
  MyProjectNameTest net10.0                                                     LoadStaticWebAssetsBuildManifest (2.8s)
dotnet watch ⌚ [FW] Deleted '/Users/borosmate/Documents/Playground/MyProjectNameTest/bin/Debug/net10.0/MyProjectNameTest'.
dotnet watch ⌚ [FW] Updated '/Users/borosmate/Documents/Playground/MyProjectNameTest/obj/Debug/net10.0/apphost'.
dotnet watch ⌚ [FW] Added '/Users/borosmate/Documents/Playground/MyProjectNameTest/obj/Debug/net10.0/apphost'.
dotnet watch ⌚ [FW] Deleted '/Users/borosmate/Documents/Playground/MyProjectNameTest/bin/Debug/net10.0/MyProjectNameTest.dll'.
dotnet watch ⌚ [FW] Updated '/Users/borosmate/Documents/Playground/MyProjectNameTest/obj/Debug/net10.0/MyProjectNameTest.dll'.
dotnet watch ⌚ [FW] Added '/Users/borosmate/Documents/Playground/MyProjectNameTest/bin/Debug/net10.0/MyProjectNameTest.dll'.
dotnet watch ⌚ [FW] Deleted '/Users/borosmate/Documents/Playground/MyProjectNameTest/obj/Debug/net10.0/ref/MyProjectNameTest.dll'.
dotnet watch ⌚ [FW] Updated '/Users/borosmate/Documents/Playground/MyProjectNameTest/obj/Debug/net10.0/refint/MyProjectNameTest.dll'.
dotnet watch ⌚ [FW] Added '/Users/borosmate/Documents/Playground/MyProjectNameTest/obj/Debug/net10.0/ref/MyProjectNameTest.dll'.
dotnet watch ⌚ [FW] Deleted '/Users/borosmate/Documents/Playground/MyProjectNameTest/bin/Debug/net10.0/MyProjectNameTest.pdb'.
dotnet watch ⌚ [FW] Updated '/Users/borosmate/Documents/Playground/MyProjectNameTest/obj/Debug/net10.0/MyProjectNameTest.pdb'.
dotnet watch ⌚ [FW] Added '/Users/borosmate/Documents/Playground/MyProjectNameTest/bin/Debug/net10.0/MyProjectNameTest.pdb'.
dbug: Microsoft.AspNetCore.Watch.BrowserRefresh.BlazorWasmHotReloadMiddleware[0]
      Middleware loaded
dbug: Microsoft.AspNetCore.Watch.BrowserRefresh.BrowserScriptMiddleware[0]
      Middleware loaded. Script /_framework/aspnetcore-browser-refresh.js (16152 B).
dbug: Microsoft.AspNetCore.Watch.BrowserRefresh.BrowserScriptMiddleware[0]
      Middleware loaded. Script /_framework/blazor-hotreload.js (776 B).
dbug: Microsoft.AspNetCore.Watch.BrowserRefresh.BrowserRefreshMiddleware[0]
      Middleware loaded: DOTNET_MODIFIABLE_ASSEMBLIES=(null), __ASPNETCORE_BROWSER_TOOLS=true
fail: Microsoft.Extensions.Hosting.Internal.Host[11]
      Hosting failed to start
      System.IO.IOException: Failed to bind to address http://127.0.0.1:5067: address already in use.
       ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use
       ---> System.Net.Sockets.SocketException (48): Address already in use
         at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, Boolean disconnectOnFailure, String callerName)
         at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
         at System.Net.Sockets.Socket.Bind(EndPoint localEP)
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass28_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
         at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__14_1(IHostedService service, CancellationToken token)
         at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
Unhandled exception. System.IO.IOException: Failed to bind to address http://127.0.0.1:5067: address already in use.
 ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use
 ---> System.Net.Sockets.SocketException (48): Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, Boolean disconnectOnFailure, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass28_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__14_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Program.<Main>$(String[] args) in /Users/borosmate/Documents/Playground/MyProjectNameTest/Program.cs:line 48
dotnet watch ⌚ Process id 94297 ran for 4307ms and exited with exit code 134.
dotnet watch ❌ Exited with error code 134
dotnet watch ⏳ Waiting for a file to change before restarting ...
```

</p>
</details>

**Comment by tmat** [comment]
Fixed in 10.0.200 by https://github.com/dotnet/sdk/pull/51632

**Comment by qwadrox** [comment]
@tmat Even though this issue is marked as fixed for 10.0.200, there have already been patch releases since then, and this problem affects a core development workflow. On macOS, Hot Reload instability significantly impacts daily productivity. When Hot Reload crashes or fails, it requires manual restarts and constant intervention. That's why **"--no-hot-reload"  is important. It affects development** (not just a niche scenario)

Would it be possible to consider bringing this fix forward into an earlier servicing release rather than waiting for 10.0.200?

I believe this has a very high real-world impact on developer productivity. I check everyday is there is a new release.

**Comment by mispencer** [comment]
@qwadrox - I believe the workaround works in 10.0.100.
